<h1> Bertopic</h1>

In this notebook, we will be running bertopic again on our collected data. We will try to get as many topics as possible in only on run since it is good for the topic alighment with other platforms.

<h2> Data prep </h2>

We will upload already ready data. We will delete the unrelavant videos with the help of the 'is_relevant' column that we have created in the previous analysis of the Topics and Subtopics.

In [1]:
import pandas as pd

df = pd.read_csv("./topics/subtopics/final_data.csv")

In [10]:
pd.set_option('display.max_rows', None)

In [3]:
df.columns

Index(['source', 'video_id', 'video_url', 'title', 'description', 'channel',
       'comments', 'views', 'likes', 'comments_count', 'keywords', 'country',
       'date', 'likes_missing', 'text', 'topic', 'is_relevant', 'subtopic'],
      dtype='object')

In [4]:
#let's only get the relevant topics
df = df[df['is_relevant']==True]

In [5]:
df.shape

(15087, 18)

In [6]:
#Let's drop the columns 'topic', 'is_relvant', 'subtopic' and 'text'
df = df.drop(columns=['topic', 'is_relevant', 'subtopic', 'text'])
df.columns

Index(['source', 'video_id', 'video_url', 'title', 'description', 'channel',
       'comments', 'views', 'likes', 'comments_count', 'keywords', 'country',
       'date', 'likes_missing'],
      dtype='object')

In [7]:
#Let's create te 'text' column again
df['text'] = df['title'].fillna("") + '. ' + df['description'].fillna("")

In [8]:
#Let's create a function which will clean the text from unwanted words

import re

def clean_text(text):
    text = re.sub(r"http\S+", "", text)      # remove URLs
    text = re.sub(r"www\S+", "", text)       # remove www links
    text = re.sub(r"\byoutube\b", "", text)  # remove "youtube"
    text = re.sub(r"\bvideo\b", "", text)    # remove "video"
    text = re.sub(r"\bwatch\b", "", text)    # remove "watch"
    text = re.sub(r"[^a-zA-Z\s]", " ", text) # keep only words
    return text.lower().strip()

In [9]:
df["clean_text"] = df["text"].fillna("").map(clean_text)

In [10]:
df.head()

,source,video_id,video_url,title,description,channel,comments,views,likes,comments_count,keywords,country,date,likes_missing,text,clean_text
0,YouTube,Mp6qdlHJyyI,https://www.youtube.com/watch?v=Mp6qdlHJyyI,Food for Seniors,Food for seniors is an important concern. Food...,GracefulAging,NaN,661.0,1.0,0.0,healthy aging,unknown,2010-01-03,False,Food for Seniors. Food for seniors is an impor...,food for seniors food for seniors is an impor...
1,YouTube,FxTc69tuOBA,https://www.youtube.com/watch?v=FxTc69tuOBA,Joe Rogan ~ DMT Is A Portal To The After Life,Joe Rogan explains his experience with DMT (Di...,Alistar Valadez,Great channel. After 5Meo I stopped lookung at...,144742.0,889.0,288.0,nootropics,unknown,2010-01-03,False,Joe Rogan ~ DMT Is A Portal To The After Life....,joe rogan dmt is a portal to the after life ...
2,YouTube,bWrlSE-LDdc,https://www.youtube.com/watch?v=bWrlSE-LDdc,THE KUROTEL SPA AND LONGEVITY CENTER,THE KUROTEL SPA AND LONGEVITY CENTER With an i...,Better Living - Travel. Food. Home. Lifestyle.,NaN,1067.0,2.0,0.0,longevity,en,2010-01-03,False,THE KUROTEL SPA AND LONGEVITY CENTER. THE KURO...,the kurotel spa and longevity center the kuro...
3,YouTube,EgOeF0YZu-A,https://www.youtube.com/watch?v=EgOeF0YZu-A,Coconut Kefir Margarita @ Longevity Conference...,Follow J-Wro on these sites (scroll down for m...,Jason Wrobel,NOTE TO ALL FANS OF DAVID AVOCADO WOLFE: Avoca...,2469.0,9.0,2.0,longevity,unknown,2010-01-03,False,Coconut Kefir Margarita @ Longevity Conference...,coconut kefir margarita longevity conference...
4,YouTube,7VVTsotiIms,https://www.youtube.com/watch?v=7VVTsotiIms,Qi Gong 10 symbols of Longevity Exercises 1-6,This rarely known in America set of Qi Gong Ex...,Luis Duarte Tai Chi & Qi Gong,"💖👏👏👏🙏🇵🇹 || Graciad profesor luis || Que Joven,...",401312.0,2249.0,191.0,longevity,en-US,2010-01-03,False,Qi Gong 10 symbols of Longevity Exercises 1-6....,qi gong symbols of longevity exercises ...

<h2> Bertopic run</h2>

In [11]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/azim/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [11]:
import umap
from hdbscan import HDBSCAN
from bertopic import BERTopic
from nltk.corpus import stopwords
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

# Embedding model
model = SentenceTransformer("paraphrase-mpnet-base-v2")

# Custom stopwords
custom_stopwords = list(stopwords.words("english")) + ["http", "https", "youtube", "video", "videos", "watch", "channel", "subscribe", "com"]

# Vectorizer
vectorizer_model = CountVectorizer(
    stop_words=custom_stopwords,
    ngram_range=(1, 2),
    max_df=0.85,
    min_df=2,
    max_features=3000
)

# UMAP
umap_model = umap.UMAP(
    n_neighbors=15,
    n_components=5,
    min_dist=0.0,
    random_state=42
)

# HDBSCAN
hdbscan_model = HDBSCAN(
    min_cluster_size=20,
    min_samples=5,
    cluster_selection_epsilon=0.0,
    prediction_data=True
)

# BERTopic
topic_model = BERTopic(
    embedding_model=model,
    vectorizer_model=vectorizer_model,
    hdbscan_model=hdbscan_model,
    umap_model=umap_model,
    nr_topics=None,
    top_n_words=10,
    calculate_probabilities=True,
)

In [12]:
topics, probs = topic_model.fit_transform(df['clean_text'].fillna("").tolist())

In [13]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,5266,-1_anti_anti aging_healthy_healthy aging,"[anti, anti aging, healthy, healthy aging, ski...",[anti aging skin care products anti aging ski...
1,0,1875,0_biohacking_biohacker_biohack_dave,"[biohacking, biohacker, biohack, dave, asprey,...",[biohacking is amazing biohacking...
2,1,899,1_longevity_human longevity_human_live,"[longevity, human longevity, human, live, long...","[lesson longevity, pcf longevity pcf long..."
3,2,427,2_facial rejuvenation_facial_plastic_surgery,"[facial rejuvenation, facial, plastic, surgery...","[nyt alison facial rejuvenation, aiello ..."
4,3,391,3_exercise_fitness_training_fit,"[exercise, fitness, training, fit, exercises, ...",[fit body fit mind your practical guide to ag...
5,4,374,4_brain_focus_nootropics_memory,"[brain, focus, nootropics, memory, boost, supp...",[how to boost brain power nootropics supplem...
6,5,235,5_brain_alzheimer_dementia_aging brain,"[brain, alzheimer, dementia, aging brain, brai...",[how much sleep do i need brain rules for ag...
7,6,217,6_nutrition_eating_aging nutrition_diet,"[nutrition, eating, aging nutrition, diet, foo...","[aging and nutrition, iff healthy aging nutr..."
8,7,191,7_laser_laser skin_skin rejuvenation_skin,"[laser, laser skin, skin rejuvenation, skin, r...",[laser skin rejuvenation visit laser skin ...
9,8,191,8_cortex_cortex nootropic_stack torque_socials...,"[cortex, cortex nootropic, stack torque, socia...",[these nootropics are all you need our pro...
10,9,175,9_hand_hand rejuvenation_hands_radiesse,"[hand, hand rejuvenation, hands, radiesse, rej...","[hand rejuvenation, hand rejuvenation with rej..."
11,10,172,10_caring_center healthy_healthy aging_caregivers,"[caring, center healthy, healthy aging, caregi...",[be well boston caring for aging parents clo...
12,11,159,11_nootropics_nootropic_best nootropics_best,"[nootropics, nootropic, best nootropics, best,...","[nootropics, nootropics slides to, are nootr..."
13,12,143,12_routine_skincare routine_skincare_aging ski...,"[routine, skincare routine, skincare, aging sk...",[anti aging skincare to treat wrinkles and plu...
14,13,132,13_well america_america_aging well_marie,"[well america, america, aging well, marie, ann...",[aging well in america with guest sadie bolos ...
15,14,125,14_drugs_smart drugs_smart_students,"[drugs, smart drugs, smart, students, college,...","[scienziati della droga smart drugs, smart d..."
16,15,120,15_retinol_tretinoin_retin_bakuchiol,"[retinol, tretinoin, retin, bakuchiol, cream, ...","[murad retinol anti aging skincare, retinol ..."
17,16,113,16_aging well_well_kitv aging_kitv,"[aging well, well, kitv aging, kitv, planning,...","[aging well named well, fitchburg wi commis..."
18,17,113,17_population_poll_poll healthy_national poll,"[population, poll, poll healthy, national poll...",[americans don t seek enough help with pre...
19,18,111,18_skin rejuvenation_skin_rejuvenation_peel,"[skin rejuvenation, skin, rejuvenation, peel, ...","[xeo blossom skin rejuvenation, dermaheal hsr ..."
20,19,110,19_vaginal_rejuvenation_feminine_laser,"[vaginal, rejuvenation, feminine, laser, proce...","[thermiva vaginal rejuvenation, femilift vagin..."
21,20,105,20_well_aging well_age_positive,"[well, aging well, age, positive, well aging, ...",[aging well how to age well the final wor...
22,21,93,21_diet_longevity diet_longevity_food,"[diet, longevity diet, longevity, food, raw, e...",[longevity diet module practical cooking wi...
23,22,90,22_serum_aging serum_vitamin_vitamin serum,"[serum, aging serum, vitamin, vitamin serum, s...",[vitamin c serum dermaceutic laboratorie tr...
24,23,78,23_women_menopause_men_meschino,"[women, menopause, men, meschino, expert advic...",[natural healthy aging women importa...
25,24,78,24_piracetam_aniracetam_phenylpiracetam_choline,"[piracetam, aniracetam, phenylpiracetam, choli...",[aniracetam to reduce anxiety aniracetam to r...
26,25,75,25_rejuvenation health_rejuvenation_health ser...,"[rejuvenation health, rejuvenation, health ser...",[rejuvenation health services mva early interv...
27,26,75,26_anti aging_anti_aging anti_ingredients,"[anti aging, anti, aging anti, ingredients, ag...","[anti aging anti aging with own products, nag..."
28,27,74,27_cream_aging cream_creams_best anti,"[cream, aging cream, creams, best anti, aging ...","[anti aging cream anti aging cream, anti agin..."
29,28,70,28_energy_pre workout_pre_nootropic,"[energy, pre workout, pre, nootropic, workout,...",[sweating through workouts try these newhist...
30,29,68,29_prp_plasma_platelet_platelet rich,"[prp, plasma, platelet, platelet rich, rich pl...",[prp and prf rejuvenation platelet rich plasm...
31,30,65,30_aging insights_insights_njfa_melissa,"[aging insights, insights, njfa, melissa, dire...",[aging insights addiction and seniors thi...
32,31,65,31_aging foods_foods_fruits_best anti,"[aging foods, foods, fruits, best anti, younge...",[top anti aging foods learn more about ant...
33,32,63,32_fasting_longo_valter_valter longo,"[fasting, longo, valter, valter longo, intermi...",[dr valter longo explains the longevity diet ...
34,33,60,33_tips healthy_healthy_tips_healthy aging,"[tips healthy, healthy, tips, healthy aging, h...","[tips for healthy aging, tips for healthy agin..."
35,34,59,34_yoga_breathing_bell_practice,"[yoga, breathing, bell, practice, meditation, ...",[yoga for healthy aging with avatara yoga yog...
36,35,56,35_heart_vascular_cardiovascular_heart health,"[heart, vascular, cardiovascular, heart health...",[healthy aging heart health opening blocked...
37,36,54,36_sleep_melatonin_better sleep_sleeping,"[sleep, melatonin, better sleep, sleeping, pat...",[healthy aging sleep getting a good night ...
38,37,54,37_cosmetics_information buy_buy_brush,"[cosmetics, information buy, buy, brush, infor...",[it cosmetics anti aging celebration foundatio...
39,38,54,38_treatments_aging treatments_anti_anti aging,"[treatments, aging treatments, anti, anti agin...",[plastic surgeon ranks anti aging treatment...
40,39,53,39_well la_la_aging well_well,"[well la, la, aging well, well, move, transiti...","[aging well in la aging gay, aging well in..."
41,40,53,40_aging healthy_healthy aging_healthy_healthy...,"[aging healthy, healthy aging, healthy, health...","[healthy aging, healthy aging healthy aging,..."
42,41,50,41_qvc_buy previously_previously recorded_qvc ...,"[qvc, buy previously, previously recorded, qvc...",[newa by endymed medical skin rejuvenation dev...
43,42,49,42_led_light_light therapy_therapy,"[led, light, light therapy, therapy, device, l...",[led light therapy facial photon device for he...
44,43,47,43_muscle_protein_muscle mass_mass,"[muscle, protein, muscle mass, mass, maintaini...",[this is why muscle mass is key to longevity ...
45,44,46,44_smart_smart drugs_drugs_nootropics smart,"[smart, smart drugs, drugs, nootropics smart, ...",[history of smart drugs amp the future of no...
46,45,45,45_supplements_vitamin_omega_supplement,"[supplements, vitamin, omega, supplement, gund...",[vitamin c the longevity vitamin dr steve...
47,46,45,46_demonstrating_exercise_shoulder_rehabilitation,"[demonstrating, exercise, shoulder, rehabilita...",[rejuvenation shoulder press rejuvenation p...
48,47,45,47_eyelid_eyelid rejuvenation_eye_eye rejuvena...,"[eyelid, eyelid rejuvenation, eye, eye rejuven...",[dr jeffrey rawnsley eyelid rejuvenation d...
49,48,45,48_oral_oral health_dental_dentistry,"[oral, oral health, dental, dentistry, implant...",[oral health for an ageing population oral he...
50,49,44,49_stem_cell_stem cell_cell rejuvenation,"[stem, cell, stem cell, cell rejuvenation, ste...","[stem cell rejuvenation injection, rejuvenatio..."
51,50,44,50_massage_face_face yoga_face massage,"[massage, face, face yoga, face massage, yoga,...",[best face yoga for glowing skin facial exer...
52,51,43,51_healing_reiki_music_regeneration,"[healing, reiki, music, regeneration, frequenc...",[super fast help from divine forces health ...
53,52,42,52_foods_aging foods_food_eat,"[foods, aging foods, food, eat, signs, nutrien...",[foods to keep from aging foods to keep from ...
54,53,42,53_fillers_filler_botox_dermal,"[fillers, filler, botox, dermal, dermal filler...",[botox vs filler facial rejuvenation botox an...
55,54,41,54_peptides_peptide_copper_retinol,"[peptides, peptide, copper, retinol, skincare,...",[top peptide serums for anti aging shortsvi...
56,55,40,55_aging month_month_september_september healthy,"[aging month, month, september, september heal...",[september is health aging month september...
57,56,39,56_qigong_tai chi_chi_tai,"[qigong, tai chi, chi, tai, gong, qi, qi gong,...",[tai chi longevity stick program balance ...
58,57,39,57_research_aging research_lecture_university,"[research, aging research, lecture, university...",[conference on aging with keynote speaker lind...
59,58,38,58_dentistry_gum_dental_mouth,"[dentistry, gum, dental, mouth, dentist, smile...",[scottsdale smiles dentistry offers pinhole gu...
60,59,38,59_alpha brain_alpha_onnit_brain,"[alpha brain, alpha, onnit, brain, joe rogan, ...",[alpha brain review real user experience onnit...
61,60,38,60_noopept_nootropic benefits_nootropic_including,"[noopept, nootropic benefits, nootropic, inclu...",[valerian in this you ll discover the nootro...
62,61,37,61_falls_fall_fall prevention_prevention,"[falls, fall, fall prevention, prevention, pre...",[healthy aging and fall prevention summit in...
63,62,37,62_telomeres_telomere_cells_length,"[telomeres, telomere, cells, length, support, ...",[how well are you aging life length telomer...
64,63,37,63_fellowship_aging medicine_meet_medicine,"[fellowship, aging medicine, meet, medicine, a...",[tamara densmore m d a m anti aging fellowshi...
65,64,35,64_collagen_supplement_beauty_super,"[collagen, supplement, beauty, super, skin, su...",[beyond beauty collagen supplementation for h...
66,65,34,65_lip_lip rejuvenation_fat_transfer,"[lip, lip rejuvenation, fat, transfer, fat tra...",[perioral and lip rejuvenation with fillers dr...
67,66,34,66_nmn_nad_resveratrol_pro,"[nmn, nad, resveratrol, pro, levels, lifespan,...",[prohealth longevity nmn pro highest quality...
68,67,33,67_ipl_intense_pulsed_light,"[ipl, intense, pulsed, light, photo, photo rej...",[neck rejuvenation with ipl treament have you...
69,68,33,68_microneedling_micro_rf_skin,"[microneedling, micro, rf, skin, skin rejuvena...",[exion microneedling rf skincare skins ...
70,69,32,69_ayurveda_ayurvedic_detox_india,"[ayurveda, ayurvedic, detox, india, healing, r...",[somatheeram ayurvedic rejuvenation package ...
71,70,32,70_mental health_mental_depression_aging speaker,"[mental health, mental, depression, aging spea...",[frhc mental health facts about aging depressi...
72,71,32,71_aging month_month_tips healthy_tips,"[aging month, month, tips healthy, tips, healt...",[healthy aging month with dr contessa metcalf...
73,72,31,72_orlando_eterna_medical rejuvenation_orlando fl,"[orlando, eterna, medical rejuvenation, orland...",[colombian liposculpture eterna md medical r...
74,73,31,73_technology_technologies_digital_nia,"[technology, technologies, digital, nia, commu...",[technology and health aging safely and more ...
75,74,30,74_skincare_routine_makeup_aging skincare,"[skincare, routine, makeup, aging skincare, sk...",[anti aging tips help maintain beautiful skin ...
76,75,29,75_stem_cells_cell_stem cells,"[stem, cells, cell, stem cells, cell therapy, ...",[a closer look at stem cells and human longe...
77,76,29,76_information buy_buy_algenist_information,"[information buy, buy, algenist, information, ...",[algenist genius anti aging moisturizer amp ...
78,77,28,77_oils_oil_essential oils_essential,"[oils, oil, essential oils, essential, skin, g...",[the best anti aging skin care oils chris ...
79,78,28,78_place_homes_communities_aging place,"[place, homes, communities, aging place, home,...",[designing homes and neighborhoods for an agin...
80,79,28,79_hormone_hormones_therapy_balance,"[hormone, hormones, therapy, balance, cure, sa...",[the hormone cure dr sara gottfried s easy t...
81,80,27,80_big think_edge exclusive_daily join_new daily,"[big think, edge exclusive, daily join, new da...",[what s your counsel new videos daily ...
82,81,27,81_sublative_sublative rejuvenation_ematrix_re...,"[sublative, sublative rejuvenation, ematrix, r...",[sublative rejuvenation sublative rejuvenatio...
83,82,27,82_youtubeshorts_shorts_dermatologist_skincare,"[youtubeshorts, shorts, dermatologist, skincar...",[shorts dermatologist shops for anti aging ski...
84,83,26,83_olay_aging body_advanced anti_cleansing,"[olay, aging body, advanced anti, cleansing, t...",[anti aging beauty tips and olay total effect...
85,84,26,84_best anti_aging skin_products_skin care,"[best anti, aging skin, products, skin care, c...",[the best anti aging skin care under dr d...
86,85,25,85_pause_pause well_well aging_base,"[pause, pause well, well aging, base, agency, ...",[base beauty creative agency pause well agin...
87,86,24,86_coffee_mushroom_mane_lion mane,"[coffee, mushroom, mane, lion mane, lion, mush...",[lion s mane mushroom is underrated lio...
88,87,23,87_eye_vision_eye health_eyes,"[eye, vision, eye health, eyes, aging eye, agi...",[national healthy aging month eye health dr ...
89,88,23,88_metformin_rapamycin_drug_nmn,"[metformin, rapamycin, drug, nmn, trial, huber...",[metformin and toxic junk is that the secret ...
90,89,23,89_qualia_qualia mind_mind_powerful nootropic,"[qualia, qualia mind, mind, powerful nootropic...",[qualia mind review edition qualiali...
91,90,23,90_speaker_aging well_martin_linda,"[speaker, aging well, martin, linda, discusses...",[tedxmsvu aging well am lie lemieux am lie ...
92,91,22,91_neurofeedback_therapy_orange_healing,"[neurofeedback, therapy, orange, healing, book...",[is neurofeedback therapy a useful therapy i...
93,92,22,92_mask_face mask_masks_face,"[mask, face mask, masks, face, homemade, organ...",[diy anti aging face mask for wrinkle free ski...
94,93,22,93_medicare_well ep_seg_elder,"[medicare, well ep, seg, elder, abuse, ep, pro...",[aging well ep seg things to know when ...
95,94,22,94_reality_reproductive_making_amp healthy,"[reality, reproductive, making, amp healthy, m...",[making reproductive longevity a reality epi...
96,95,22,95_aging bb_bb cream_hydroxatone_bb,"[aging bb, bb cream, hydroxatone, bb, hydroxat...",[hydroxatone anti aging bb cream erin s a...
97,96,22,96_adhd_add_best nootropics_nootropics,"[adhd, add, best nootropics, nootropics, advan...",[best nootropics for adhd nootropicsforadhd ...
98,97,22,97_meditation_healing_guided_heal,"[meditation, healing, guided, heal, sleep, rel...",[sleep hypnosis for pain relief and body heali...
99,98,22,98_aging tips_tips_beauty_well aging,"[aging tips, tips, beauty, well aging, facts, ...",[anti aging tips for women just because ...
100,99,21,99_aubrey_aubrey de_de grey_grey,"[aubrey, aubrey de, de grey, grey, sens, de, f...",[in pursuit of longevity with aubrey de grey ...
101,100,21,100_others take_quiz_unstoppable_nootropics bi...,"[others take, quiz, unstoppable, nootropics bi...",[how to take l theanine with coffee shorts n...
102,101,21,101_pain_pain relief_rehab_relief,"[pain, pain relief, rehab, relief, longevity r...",[longevity usa thank you photos longevi...
103,102,21,102_modafinil_adderall_world first_alternatives,"[modafinil, adderall, world first, alternative...",[adderall alternatives otc adderall alternat...
104,103,21,103_stop_clock_reverse_biological,"[stop, clock, reverse, biological, turn, time,...",[using anti aging longevity science you can no...
105,104,21,104_aged_aged well_surgeon_reacts,"[aged, aged well, surgeon, reacts, double boar...",[has erika jayne aged well surgeon reacts ...
106,105,20,105_aging skin_na_skin_wish,"[aging skin, na, skin, wish, skin care, anti a...","[anti aging skin care the lancer method, dr e..."
107,106,20,106_fraxel_laser_dual_treatment,"[fraxel, laser, dual, treatment, skin rejuvena...",[best laser for anti aging before and after ...
108,107,20,107_loneliness_isolation_social_connection,"[loneliness, isolation, social, connection, ol...",[promoting healthy aging and taking bold actio...

<h3> Saving </h3>

In [15]:
tpp = topic_model.get_topic_info()

In [17]:
import numpy as np
import pandas as pd
import pickle


tpp.to_csv('./topics_2/topics_before/mpnet_topics.csv', index=False)
topic_model.save("./topics_2/topics/mpnet_topic_model")
np.save('./topics_2/topics/topic_probabilities.npy', probs)

preprocessed_data = df['clean_text'].fillna("").tolist()
with open('./topics_2/topics/preprocessed_data.pkl', 'wb') as f:
    pickle.dump(preprocessed_data, f)

2025-09-03 02:53:51,824 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

In [18]:
st = SentenceTransformer("paraphrase-mpnet-base-v2")
def embed(texts):
    return st.encode(texts, batch_size=128, normalize_embeddings=True, show_progress_bar=True)

X = embed(df['clean_text'].fillna("").tolist()).astype("float32")
np.save("./topics_2/topics/embeddings.npy", X)

Batches:   0%|          | 0/118 [00:00<?, ?it/s]

In [20]:
#Saving without UMAP
topic_model.umap_model = None
topic_model.save("./topics_2/topics/mpnet_topic_model_no_umap")

2025-09-03 03:12:43,491 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

In [21]:
#Assigning the topics
df['topic']=topics

#saving the data
df.to_csv("./topics_2/topics_before/data.csv", index=False)

<h2> Bertopics analysis </h2>

In [2]:
import pandas as pd

df = pd.read_csv("./topics_2/topics_before/data.csv")
tp = pd.read_csv("./topics_2/topics_before/mpnet_topics.csv")

In [12]:
#function to check if the video is related or unrelated

def is_video_related(text, keywords):
    text = str(text).lower()
    return any(kw in text for kw in keywords)

def check_relevance_ratio(df, topic_id, keywords):
    df_topic = df[df['topic']==topic_id]
    relevant_count = df_topic['clean_text'].apply(lambda x: is_video_related(x, keywords)).sum()
    return relevant_count/len(df_topic)

keywords = ["longevity", "healthy aging", "biohacking", "rejuvenation", "anti-aging", "nootropics", "health", "well-aging",
            "aging well", "aging"]

tp['relevance_ratio'] = tp['Topic'].apply(lambda t: check_relevance_ratio(df, t, keywords))

In [13]:
tp

,Topic,Count,Name,Representation,Representative_Docs,relevance_ratio
0,-1,5266,-1_anti_anti aging_healthy_healthy aging,"['anti', 'anti aging', 'healthy', 'healthy agi...",['anti aging skin care products anti aging sk...,0.885302
1,0,1875,0_biohacking_biohacker_biohack_dave,"['biohacking', 'biohacker', 'biohack', 'dave',...",['biohacking is amazing biohackin...,0.782933
2,1,899,1_longevity_human longevity_human_live,"['longevity', 'human longevity', 'human', 'liv...","['lesson longevity', 'pcf longevity pcf l...",0.975528
3,2,427,2_facial rejuvenation_facial_plastic_surgery,"['facial rejuvenation', 'facial', 'plastic', '...","['nyt alison facial rejuvenation', 'aiello...",0.957845
4,3,391,3_exercise_fitness_training_fit,"['exercise', 'fitness', 'training', 'fit', 'ex...",['fit body fit mind your practical guide to a...,0.915601
5,4,374,4_brain_focus_nootropics_memory,"['brain', 'focus', 'nootropics', 'memory', 'bo...",['how to boost brain power nootropics supple...,0.745989
6,5,235,5_brain_alzheimer_dementia_aging brain,"['brain', 'alzheimer', 'dementia', 'aging brai...",['how much sleep do i need brain rules for a...,0.914894
7,6,217,6_nutrition_eating_aging nutrition_diet,"['nutrition', 'eating', 'aging nutrition', 'di...","['aging and nutrition', 'iff healthy aging n...",0.935484
8,7,191,7_laser_laser skin_skin rejuvenation_skin,"['laser', 'laser skin', 'skin rejuvenation', '...",['laser skin rejuvenation visit laser skin...,0.947644
9,8,191,8_cortex_cortex nootropic_stack torque_socials...,"['cortex', 'cortex nootropic', 'stack torque',...",['these nootropics are all you need our pr...,0.958115
10,9,175,9_hand_hand rejuvenation_hands_radiesse,"['hand', 'hand rejuvenation', 'hands', 'radies...","['hand rejuvenation', 'hand rejuvenation with ...",0.994286
11,10,172,10_caring_center healthy_healthy aging_caregivers,"['caring', 'center healthy', 'healthy aging', ...",['be well boston caring for aging parents cl...,0.982558
12,11,159,11_nootropics_nootropic_best nootropics_best,"['nootropics', 'nootropic', 'best nootropics',...","['nootropics', 'nootropics slides to', 'are ...",0.924528
13,12,143,12_routine_skincare routine_skincare_aging ski...,"['routine', 'skincare routine', 'skincare', 'a...",['anti aging skincare to treat wrinkles and pl...,0.958042
14,13,132,13_well america_america_aging well_marie,"['well america', 'america', 'aging well', 'mar...",['aging well in america with guest sadie bolos...,0.969697
15,14,125,14_drugs_smart drugs_smart_students,"['drugs', 'smart drugs', 'smart', 'students', ...","['scienziati della droga smart drugs', 'smar...",0.104000
16,15,120,15_retinol_tretinoin_retin_bakuchiol,"['retinol', 'tretinoin', 'retin', 'bakuchiol',...","['murad retinol anti aging skincare', 'retinol...",0.858333
17,16,113,16_aging well_well_kitv aging_kitv,"['aging well', 'well', 'kitv aging', 'kitv', '...","['aging well named well', 'fitchburg wi com...",0.991150
18,17,113,17_population_poll_poll healthy_national poll,"['population', 'poll', 'poll healthy', 'nation...",['americans don t seek enough help with pr...,1.000000
19,18,111,18_skin rejuvenation_skin_rejuvenation_peel,"['skin rejuvenation', 'skin', 'rejuvenation', ...","['xeo blossom skin rejuvenation', 'dermaheal h...",1.000000
20,19,110,19_vaginal_rejuvenation_feminine_laser,"['vaginal', 'rejuvenation', 'feminine', 'laser...","['thermiva vaginal rejuvenation', 'femilift va...",0.972727
21,20,105,20_well_aging well_age_positive,"['well', 'aging well', 'age', 'positive', 'wel...",['aging well how to age well the final wo...,0.961905
22,21,93,21_diet_longevity diet_longevity_food,"['diet', 'longevity diet', 'longevity', 'food'...",['longevity diet module practical cooking w...,0.946237
23,22,90,22_serum_aging serum_vitamin_vitamin serum,"['serum', 'aging serum', 'vitamin', 'vitamin s...",['vitamin c serum dermaceutic laboratorie t...,0.966667
24,23,78,23_women_menopause_men_meschino,"['women', 'menopause', 'men', 'meschino', 'exp...",['natural healthy aging women import...,0.948718
25,24,78,24_piracetam_aniracetam_phenylpiracetam_choline,"['piracetam', 'aniracetam', 'phenylpiracetam',...",['aniracetam to reduce anxiety aniracetam to ...,0.461538
26,25,75,25_rejuvenation health_rejuvenation_health ser...,"['rejuvenation health', 'rejuvenation', 'healt...",['rejuvenation health services mva early inter...,0.973333
27,26,75,26_anti aging_anti_aging anti_ingredients,"['anti aging', 'anti', 'aging anti', 'ingredie...","['anti aging anti aging with own products', '...",0.986667
28,27,74,27_cream_aging cream_creams_best anti,"['cream', 'aging cream', 'creams', 'best anti'...","['anti aging cream anti aging cream', 'anti a...",0.959459
29,28,70,28_energy_pre workout_pre_nootropic,"['energy', 'pre workout', 'pre', 'nootropic', ...",['sweating through workouts try these newhis...,0.671429
30,29,68,29_prp_plasma_platelet_platelet rich,"['prp', 'plasma', 'platelet', 'platelet rich',...",['prp and prf rejuvenation platelet rich plas...,0.941176
31,30,65,30_aging insights_insights_njfa_melissa,"['aging insights', 'insights', 'njfa', 'meliss...",['aging insights addiction and seniors th...,0.876923
32,31,65,31_aging foods_foods_fruits_best anti,"['aging foods', 'foods', 'fruits', 'best anti'...",['top anti aging foods learn more about an...,0.969231
33,32,63,32_fasting_longo_valter_valter longo,"['fasting', 'longo', 'valter', 'valter longo',...",['dr valter longo explains the longevity diet...,0.952381
34,33,60,33_tips healthy_healthy_tips_healthy aging,"['tips healthy', 'healthy', 'tips', 'healthy a...","['tips for healthy aging', 'tips for healthy a...",1.000000
35,34,59,34_yoga_breathing_bell_practice,"['yoga', 'breathing', 'bell', 'practice', 'med...",['yoga for healthy aging with avatara yoga yo...,0.949153
36,35,56,35_heart_vascular_cardiovascular_heart health,"['heart', 'vascular', 'cardiovascular', 'heart...",['healthy aging heart health opening blocke...,0.946429
37,36,54,36_sleep_melatonin_better sleep_sleeping,"['sleep', 'melatonin', 'better sleep', 'sleepi...",['healthy aging sleep getting a good night ...,0.888889
38,37,54,37_cosmetics_information buy_buy_brush,"['cosmetics', 'information buy', 'buy', 'brush...",['it cosmetics anti aging celebration foundati...,1.000000
39,38,54,38_treatments_aging treatments_anti_anti aging,"['treatments', 'aging treatments', 'anti', 'an...",['plastic surgeon ranks anti aging treatmen...,0.944444
40,39,53,39_well la_la_aging well_well,"['well la', 'la', 'aging well', 'well', 'move'...","['aging well in la aging gay', 'aging well...",1.000000
41,40,53,40_aging healthy_healthy aging_healthy_healthy...,"['aging healthy', 'healthy aging', 'healthy', ...","['healthy aging', 'healthy aging healthy agi...",1.000000
42,41,50,41_qvc_buy previously_previously recorded_qvc ...,"['qvc', 'buy previously', 'previously recorded...",['newa by endymed medical skin rejuvenation de...,0.940000
43,42,49,42_led_light_light therapy_therapy,"['led', 'light', 'light therapy', 'therapy', '...",['led light therapy facial photon device for h...,0.959184
44,43,47,43_muscle_protein_muscle mass_mass,"['muscle', 'protein', 'muscle mass', 'mass', '...",['this is why muscle mass is key to longevity ...,0.957447
45,44,46,44_smart_smart drugs_drugs_nootropics smart,"['smart', 'smart drugs', 'drugs', 'nootropics ...",['history of smart drugs amp the future of n...,0.891304
46,45,45,45_supplements_vitamin_omega_supplement,"['supplements', 'vitamin', 'omega', 'supplemen...",['vitamin c the longevity vitamin dr stev...,0.977778
47,46,45,46_demonstrating_exercise_shoulder_rehabilitation,"['demonstrating', 'exercise', 'shoulder', 'reh...",['rejuvenation shoulder press rejuvenation ...,0.600000
48,47,45,47_eyelid_eyelid rejuvenation_eye_eye rejuvena...,"['eyelid', 'eyelid rejuvenation', 'eye', 'eye ...",['dr jeffrey rawnsley eyelid rejuvenation ...,0.977778
49,48,45,48_oral_oral health_dental_dentistry,"['oral', 'oral health', 'dental', 'dentistry',...",['oral health for an ageing population oral h...,0.933333
50,49,44,49_stem_cell_stem cell_cell rejuvenation,"['stem', 'cell', 'stem cell', 'cell rejuvenati...","['stem cell rejuvenation injection', 'rejuvena...",0.818182
51,50,44,50_massage_face_face yoga_face massage,"['massage', 'face', 'face yoga', 'face massage...",['best face yoga for glowing skin facial exe...,0.727273
52,51,43,51_healing_reiki_music_regeneration,"['healing', 'reiki', 'music', 'regeneration', ...",['super fast help from divine forces health ...,0.860465
53,52,42,52_foods_aging foods_food_eat,"['foods', 'aging foods', 'food', 'eat', 'signs...",['foods to keep from aging foods to keep from...,0.928571
54,53,42,53_fillers_filler_botox_dermal,"['fillers', 'filler', 'botox', 'dermal', 'derm...",['botox vs filler facial rejuvenation botox a...,0.976190
55,54,41,54_peptides_peptide_copper_retinol,"['peptides', 'peptide', 'copper', 'retinol', '...",['top peptide serums for anti aging shortsv...,1.000000
56,55,40,55_aging month_month_september_september healthy,"['aging month', 'month', 'september', 'septemb...",['september is health aging month septembe...,1.000000
57,56,39,56_qigong_tai chi_chi_tai,"['qigong', 'tai chi', 'chi', 'tai', 'gong', 'q...",['tai chi longevity stick program balance...,1.000000
58,57,39,57_research_aging research_lecture_university,"['research', 'aging research', 'lecture', 'uni...",['conference on aging with keynote speaker lin...,0.897436
59,58,38,58_dentistry_gum_dental_mouth,"['dentistry', 'gum', 'dental', 'mouth', 'denti...",['scottsdale smiles dentistry offers pinhole g...,1.000000
60,59,38,59_alpha brain_alpha_onnit_brain,"['alpha brain', 'alpha', 'onnit', 'brain', 'jo...",['alpha brain review real user experience onni...,0.289474
61,60,38,60_noopept_nootropic benefits_nootropic_including,"['noopept', 'nootropic benefits', 'nootropic',...",['valerian in this you ll discover the nootr...,0.289474
62,61,37,61_falls_fall_fall prevention_prevention,"['falls', 'fall', 'fall prevention', 'preventi...",['healthy aging and fall prevention summit i...,0.972973
63,62,37,62_telomeres_telomere_cells_length,"['telomeres', 'telomere', 'cells', 'length', '...",['how well are you aging life length telome...,1.000000
64,63,37,63_fellowship_aging medicine_meet_medicine,"['fellowship', 'aging medicine', 'meet', 'medi...",['tamara densmore m d a m anti aging fellowsh...,0.891892
65,64,35,64_collagen_supplement_beauty_super,"['collagen', 'supplement', 'beauty', 'super', ...",['beyond beauty collagen supplementation for ...,0.885714
66,65,34,65_lip_lip rejuvenation_fat_transfer,"['lip', 'lip rejuvenation', 'fat', 'transfer',...",['perioral and lip rejuvenation with fillers d...,0.941176
67,66,34,66_nmn_nad_resveratrol_pro,"['nmn', 'nad', 'resveratrol', 'pro', 'levels',...",['prohealth longevity nmn pro highest qualit...,0.970588
68,67,33,67_ipl_intense_pulsed_light,"['ipl', 'intense', 'pulsed', 'light', 'photo',...",['neck rejuvenation with ipl treament have yo...,0.939394
69,68,33,68_microneedling_micro_rf_skin,"['microneedling', 'micro', 'rf', 'skin', 'skin...",['exion microneedling rf skincare skins ...,0.878788
70,69,32,69_ayurveda_ayurvedic_detox_india,"['ayurveda', 'ayurvedic', 'detox', 'india', 'h...",['somatheeram ayurvedic rejuvenation package...,0.843750
71,70,32,70_mental health_mental_depression_aging speaker,"['mental health', 'mental', 'depression', 'agi...",['frhc mental health facts about aging depress...,0.906250
72,71,32,71_aging month_month_tips healthy_tips,"['aging month', 'month', 'tips healthy', 'tips...",['healthy aging month with dr contessa metcal...,1.000000
73,72,31,72_orlando_eterna_medical rejuvenation_orlando fl,"['orlando', 'eterna', 'medical rejuvenation', ...",['colombian liposculpture eterna md medical ...,1.000000
74,73,31,73_technology_technologies_digital_nia,"['technology', 'technologies', 'digital', 'nia...",['technology and health aging safely and more...,1.000000
75,74,30,74_skincare_routine_makeup_aging skincare,"['skincare', 'routine', 'makeup', 'aging skinc...",['anti aging tips help maintain beautiful skin...,0.900000
76,75,29,75_stem_cells_cell_stem cells,"['stem', 'cells', 'cell', 'stem cells', 'cell ...",['a closer look at stem cells and human long...,0.965517
77,76,29,76_information buy_buy_algenist_information,"['information buy', 'buy', 'algenist', 'inform...",['algenist genius anti aging moisturizer amp ...,1.000000
78,77,28,77_oils_oil_essential oils_essential,"['oils', 'oil', 'essential oils', 'essential',...",['the best anti aging skin care oils chris...,1.000000
79,78,28,78_place_homes_communities_aging place,"['place', 'homes', 'communities', 'aging place...",['designing homes and neighborhoods for an agi...,0.857143
80,79,28,79_hormone_hormones_therapy_balance,"['hormone', 'hormones', 'therapy', 'balance', ...",['the hormone cure dr sara gottfried s easy ...,0.785714
81,80,27,80_big think_edge exclusive_daily join_new daily,"['big think', 'edge exclusive', 'daily join', ...",['what s your counsel new videos daily ...,0.296296
82,81,27,81_sublative_sublative rejuvenation_ematrix_re...,"['sublative', 'sublative rejuvenation', 'ematr...",['sublative rejuvenation sublative rejuvenati...,1.000000
83,82,27,82_youtubeshorts_shorts_dermatologist_skincare,"['youtubeshorts', 'shorts', 'dermatologist', '...",['shorts dermatologist shops for anti aging sk...,0.888889
84,83,26,83_olay_aging body_advanced anti_cleansing,"['olay', 'aging body', 'advanced anti', 'clean...",['anti aging beauty tips and olay total effec...,1.000000
85,84,26,84_best anti_aging skin_products_skin care,"['best anti', 'aging skin', 'products', 'skin ...",['the best anti aging skin care under dr ...,1.000000
86,85,25,85_pause_pause well_well aging_base,"['pause', 'pause well', 'well aging', 'base', ...",['base beauty creative agency pause well agi...,1.000000
87,86,24,86_coffee_mushroom_mane_lion mane,"['coffee', 'mushroom', 'mane', 'lion mane', 'l...",['lion s mane mushroom is underrated li...,0.666667
88,87,23,87_eye_vision_eye health_eyes,"['eye', 'vision', 'eye health', 'eyes', 'aging...",['national healthy aging month eye health dr...,0.869565
89,88,23,88_metformin_rapamycin_drug_nmn,"['metformin', 'rapamycin', 'drug', 'nmn', 'tri...",['metformin and toxic junk is that the secret...,0.956522
90,89,23,89_qualia_qualia mind_mind_powerful nootropic,"['qualia', 'qualia mind', 'mind', 'powerful no...",['qualia mind review edition qualial...,0.956522
91,90,23,90_speaker_aging well_martin_linda,"['speaker', 'aging well', 'martin', 'linda', '...",['tedxmsvu aging well am lie lemieux am lie...,1.000000
92,91,22,91_neurofeedback_therapy_orange_healing,"['neurofeedback', 'therapy', 'orange', 'healin...",['is neurofeedback therapy a useful therapy ...,0.090909
93,92,22,92_mask_face mask_masks_face,"['mask', 'face mask', 'masks', 'face', 'homema...",['diy anti aging face mask for wrinkle free sk...,1.000000
94,93,22,93_medicare_well ep_seg_elder,"['medicare', 'well ep', 'seg', 'elder', 'abuse...",['aging well ep seg things to know when...,1.000000
95,94,22,94_reality_reproductive_making_amp healthy,"['reality', 'reproductive', 'making', 'amp hea...",['making reproductive longevity a reality ep...,1.000000
96,95,22,95_aging bb_bb cream_hydroxatone_bb,"['aging bb', 'bb cream', 'hydroxatone', 'bb', ...",['hydroxatone anti aging bb cream erin s ...,1.000000
97,96,22,96_adhd_add_best nootropics_nootropics,"['adhd', 'add', 'best nootropics', 'nootropics...",['best nootropics for adhd nootropicsforadhd ...,0.818182
98,97,22,97_meditation_healing_guided_heal,"['meditation', 'healing', 'guided', 'heal', 's...",['sleep hypnosis for pain relief and body heal...,0.545455
99,98,22,98_aging tips_tips_beauty_well aging,"['aging tips', 'tips', 'beauty', 'well aging',...",['anti aging tips for women just because...,1.000000
100,99,21,99_aubrey_aubrey de_de grey_grey,"['aubrey', 'aubrey de', 'de grey', 'grey', 'se...",['in pursuit of longevity with aubrey de grey ...,0.952381
101,100,21,100_others take_quiz_unstoppable_nootropics bi...,"['others take', 'quiz', 'unstoppable', 'nootro...",['how to take l theanine with coffee shorts ...,1.000000
102,101,21,101_pain_pain relief_rehab_relief,"['pain', 'pain relief', 'rehab', 'relief', 'lo...",['longevity usa thank you photos longev...,0.809524
103,102,21,102_modafinil_adderall_world first_alternatives,"['modafinil', 'adderall', 'world first', 'alte...",['adderall alternatives otc adderall alterna...,0.428571
104,103,21,103_stop_clock_reverse_biological,"['stop', 'clock', 'reverse', 'biological', 'tu...",['using anti aging longevity science you can n...,0.952381
105,104,21,104_aged_aged well_surgeon_reacts,"['aged', 'aged well', 'surgeon', 'reacts', 'do...",['has erika jayne aged well surgeon reacts ...,0.238095
106,105,20,105_aging skin_na_skin_wish,"['aging skin', 'na', 'skin', 'wish', 'skin car...","['anti aging skin care the lancer method', 'd...",1.000000
107,106,20,106_fraxel_laser_dual_treatment,"['fraxel', 'laser', 'dual', 'treatment', 'skin...",['best laser for anti aging before and after...,0.950000
108,107,20,107_loneliness_isolation_social_connection,"['loneliness', 'isolation', 'social', 'connect...",['promoting healthy aging and taking bold acti...,0.950000

Let's check the topics with less than the 40 percent releavance.

In [16]:
tp[tp['relevance_ratio']<0.40]

,Topic,Count,Name,Representation,Representative_Docs,relevance_ratio
15,14,125,14_drugs_smart drugs_smart_students,"['drugs', 'smart drugs', 'smart', 'students', ...","['scienziati della droga smart drugs', 'smar...",0.104000
60,59,38,59_alpha brain_alpha_onnit_brain,"['alpha brain', 'alpha', 'onnit', 'brain', 'jo...",['alpha brain review real user experience onni...,0.289474
61,60,38,60_noopept_nootropic benefits_nootropic_including,"['noopept', 'nootropic benefits', 'nootropic',...",['valerian in this you ll discover the nootr...,0.289474
81,80,27,80_big think_edge exclusive_daily join_new daily,"['big think', 'edge exclusive', 'daily join', ...",['what s your counsel new videos daily ...,0.296296
92,91,22,91_neurofeedback_therapy_orange_healing,"['neurofeedback', 'therapy', 'orange', 'healin...",['is neurofeedback therapy a useful therapy ...,0.090909
105,104,21,104_aged_aged well_surgeon_reacts,"['aged', 'aged well', 'surgeon', 'reacts', 'do...",['has erika jayne aged well surgeon reacts ...,0.238095

We got only 6 topics. However, even though the percentage is smaller than the 40 percent, it seems like they are more or less related. We can
check the top five videos for each topics and decide if they are related or not

In [17]:
#Topic number 14
df[df['topic']==14].head()

,source,video_id,video_url,title,description,channel,comments,views,likes,comments_count,keywords,country,date,likes_missing,text,clean_text,topic
1,YouTube,FxTc69tuOBA,https://www.youtube.com/watch?v=FxTc69tuOBA,Joe Rogan ~ DMT Is A Portal To The After Life,Joe Rogan explains his experience with DMT (Di...,Alistar Valadez,Great channel. After 5Meo I stopped lookung at...,144742.0,889.0,288.0,nootropics,unknown,2010-01-03,False,Joe Rogan ~ DMT Is A Portal To The After Life....,joe rogan dmt is a portal to the after life ...,14
166,YouTube,nz9piyDdfrU,https://www.youtube.com/watch?v=nz9piyDdfrU,Misuse of Common Drugs Can Be Deadly,Common over-the-counter drugs can cause danger...,CBS,LOLZ,880.0,2.0,1.0,nootropics,unknown,2010-03-23,False,Misuse of Common Drugs Can Be Deadly. Common o...,misuse of common drugs can be deadly common o...,14
218,YouTube,CSj_FdOQACw,https://www.youtube.com/watch?v=CSj_FdOQACw,Excerpt: Boosting Brain Power,"More people, especially college students, are ...",CBS,Keep telling people you were on it. They might...,13596.0,13.0,6.0,nootropics,unknown,2010-04-22,False,"Excerpt: Boosting Brain Power. More people, es...",excerpt boosting brain power more people es...,14
219,YouTube,f_wbAhVK5eA,https://www.youtube.com/watch?v=f_wbAhVK5eA,Excerpt: Boosting Brain Power,"More people, especially college students, are ...",CBS News,Wow just Wow,1198.0,3.0,1.0,nootropics,unknown,2010-04-22,False,"Excerpt: Boosting Brain Power. More people, es...",excerpt boosting brain power more people es...,14
221,YouTube,xOlNo3ECuZI,https://www.youtube.com/watch?v=xOlNo3ECuZI,Extra: Adderall &amp; Academic Achievement,"Is there pressure to take ""smart drugs"" to sta...",CBS,i&#39;ve been taking adderall for like year an...,2952.0,3.0,5.0,nootropics,en,2010-04-25,False,Extra: Adderall &amp; Academic Achievement. Is...,extra adderall amp academic achievement is...,14

Videos in this topic are related to our research. It talks about the nootropics which help to boost the abilites of the brain

In [18]:
#topic number 59
df[df['topic']==59].head()

,source,video_id,video_url,title,description,channel,comments,views,likes,comments_count,keywords,country,date,likes_missing,text,clean_text,topic
1844,YouTube,FNjXd6cAmbE,https://www.youtube.com/watch?v=FNjXd6cAmbE,New Mood™ From Onnit Labs On the Joe Rogan Exp...,"New Mood™ from Onnit Labs, is discussed by CEO...",Onnit,GOD BLESS Joe Rogan and Onnit...you dont have ...,74258.0,365.0,96.0,nootropics,unknown,2012-03-02,False,New Mood™ From Onnit Labs On the Joe Rogan Exp...,new mood from onnit labs on the joe rogan exp...,59
2023,YouTube,jkAzqZGM8TA,https://www.youtube.com/watch?v=jkAzqZGM8TA,Onnit Labs Alpha Brain and New Mood Review,My personal review of Onnit Labs Alpha Brain a...,Christian Golez,Ya apparently doesn’t work with ums. Not a goo...,16553.0,57.0,39.0,nootropics,en,2012-04-26,False,Onnit Labs Alpha Brain and New Mood Review. M...,onnit labs alpha brain and new mood review m...,59
2031,YouTube,zJGCMatfel8,https://www.youtube.com/watch?v=zJGCMatfel8,AlphaBrain - ноотроп нового поколения,Промо - видео революционного продукта Onnit La...,Onnit Russia,"На западе ноотропы очень популярны , и востреб...",11352.0,43.0,7.0,nootropics,en,2012-05-02,False,AlphaBrain - ноотроп нового поколения. Промо -...,alphabrain ...,59
2158,YouTube,lfeO3DoxBME,https://www.youtube.com/watch?v=lfeO3DoxBME,Alpha Brain review part 2 and Thank Yous,Just a quick reply to everyone that's helped p...,SixStringPirate,"Your dreams sound fucking hilarious, ha ha! Ge...",1848.0,14.0,18.0,nootropics,unknown,2012-06-09,False,Alpha Brain review part 2 and Thank Yous. Just...,alpha brain review part and thank yous just...,59
2403,YouTube,6vh00ELP-Zk,https://www.youtube.com/watch?v=6vh00ELP-Zk,Alphabrain shroomtech sport end of day one,Day one still but after it!!,Chris Wellington,I&#39;ve just had two alpha and two shroom. F...,466.0,3.0,3.0,nootropics,en,2012-09-21,False,Alphabrain shroomtech sport end of day one. Da...,alphabrain shroomtech sport end of day one da...,59

This topic is about the nootropic called alpha brain

In [19]:
#topic number 60
df[df['topic']==60].head()

,source,video_id,video_url,title,description,channel,comments,views,likes,comments_count,keywords,country,date,likes_missing,text,clean_text,topic
2036,YouTube,_LvkAHbq7NI,https://www.youtube.com/watch?v=_LvkAHbq7NI,Nootropics Series - Part 1: Nootropic Drugs an...,The aim of this lecture entitled 'The role of ...,AntiagingSystems,I take 10mg × 2 a day. It&#39;s a brain fog ki...,52592.0,374.0,41.0,nootropics,en,2012-05-04,False,Nootropics Series - Part 1: Nootropic Drugs an...,nootropics series part nootropic drugs an...,60
2439,YouTube,Tm40c2s4YK8,https://www.youtube.com/watch?v=Tm40c2s4YK8,My Thoughts on Noopept....and Alphabrain,I am currently taking noopept and alphabrain o...,anthonynlee,"Keep them coming, enjoyed a lot! || you take 1...",43445.0,273.0,133.0,nootropics,en,2012-10-06,False,My Thoughts on Noopept....and Alphabrain. I am...,my thoughts on noopept and alphabrain i am...,60
2931,YouTube,LNdk58e0RzQ,https://www.youtube.com/watch?v=LNdk58e0RzQ,My Noopept Review,Here's my youtube video review on Noopept - a ...,po3tik1,I had to take 40 mg (x2 doses) to get the effe...,14942.0,50.0,20.0,nootropics,en,2013-04-25,False,My Noopept Review. Here's my youtube video rev...,my noopept review here s my review on noope...,60
3160,YouTube,aqF7ZCQO6Cw,https://www.youtube.com/watch?v=aqF7ZCQO6Cw,[Review] LiftMode Noopept Review,This is my review of LiftMode's 5g Noopept. To...,SupplementReviews8946,You only took it a few days so dont know how y...,32088.0,210.0,59.0,nootropics,unknown,2013-07-29,False,[Review] LiftMode Noopept Review. This is my r...,review liftmode noopept review this is my re...,60
3254,YouTube,E3OZh6dxxYw,https://www.youtube.com/watch?v=E3OZh6dxxYw,[UPDATE] Liftmode Noopept Update 1,This is a follow-up update on Liftmode's Noopept.,SupplementReviews8946,I love ANKI || What is you&#39;re dose. I just...,11705.0,61.0,39.0,nootropics,unknown,2013-09-09,False,[UPDATE] Liftmode Noopept Update 1. This is a ...,update liftmode noopept update this is a f...,60

This topic contains the videos about the review of the nootropics

In [20]:
#topic number 80
df[df['topic']==80].head()

,source,video_id,video_url,title,description,channel,comments,views,likes,comments_count,keywords,country,date,likes_missing,text,clean_text,topic
1226,YouTube,DV3XjqW_xgU,https://www.youtube.com/watch?v=DV3XjqW_xgU,Michio Kaku: How to Reverse Aging | Big Think,New videos DAILY: https://bigth.ink Join Big T...,Big Think,"Want to get Smarter, Faster™?\r<br>Subscribe f...",2120423.0,25049.0,4264.0,well aging,en-US,2011-05-31,False,Michio Kaku: How to Reverse Aging | Big Think....,michio kaku how to reverse aging big think ...,80
1233,YouTube,5MeWBlKYOvw,https://www.youtube.com/watch?v=5MeWBlKYOvw,Neil deGrasse Tyson: Living and Longevity,New videos DAILY: https://bigth.ink Join Big T...,Big Think,Limited psychology about human potential. || I...,160718.0,2227.0,338.0,longevity,en-US,2011-06-03,False,Neil deGrasse Tyson: Living and Longevity. New...,neil degrasse tyson living and longevity new...,80
1248,YouTube,X57lJXW0zL0,https://www.youtube.com/watch?v=X57lJXW0zL0,What Is Evil?,New videos DAILY: https://bigth.ink Join Big T...,Big Think,Evil is repeated sadistic behaviour by usually...,21276.0,221.0,32.0,biohacking,en-US,2011-06-10,False,What Is Evil?. New videos DAILY: https://bigth...,what is evil new videos daily join big thi...,80
1265,YouTube,HjJYvLH_FGw,https://www.youtube.com/watch?v=HjJYvLH_FGw,The Neuroscience of Internet Addiction,New videos DAILY: https://bigth.ink Join Big T...,Big Think,It&#39;s so weird to watch this 13 years later...,120396.0,1491.0,188.0,nootropics,en-US,2011-06-20,False,The Neuroscience of Internet Addiction. New vi...,the neuroscience of internet addiction new vi...,80
1989,YouTube,HgywkydIil8,https://www.youtube.com/watch?v=HgywkydIil8,What is your counsel?,New videos DAILY: https://bigth.ink Join Big T...,Big Think,NaN,138.0,0.0,0.0,biohacking,en-US,2012-04-20,False,What is your counsel?. New videos DAILY: https...,what is your counsel new videos daily join...,80

This topic contains the vidoes of the channel called Big Think. Big Think is a YouTube channel and platform featuring interviews and educational content from world-renowned experts and thinkers, designed to help viewers "get smarter, faster" by exploring big ideas and essential skills for the 21st century.

In [21]:
#topic number 91
df[df['topic']==91].head()

,source,video_id,video_url,title,description,channel,comments,views,likes,comments_count,keywords,country,date,likes_missing,text,clean_text,topic
57,YouTube,LI2319Vcs_M,https://www.youtube.com/watch?v=LI2319Vcs_M,Author of Neurofeedback Book discussing &#39;Z...,Dr. Clare Albright is a psychologist and the a...,C Albright,NaN,2431.0,0.0,0.0,nootropics,en,2010-01-29,False,Author of Neurofeedback Book discussing &#39;Z...,author of neurofeedback book discussing z...,91
68,YouTube,RPrPL6WJ4ls,https://www.youtube.com/watch?v=RPrPL6WJ4ls,Holistic Brain Neurotherapy: Retrain Your Brain,"For Beyond 50's ""Natural Healing"" talks, watch...",Daniel Davis,&quot;You have too many high frequencies in th...,36342.0,137.0,7.0,nootropics,unknown,2010-02-03,False,Holistic Brain Neurotherapy: Retrain Your Brai...,holistic brain neurotherapy retrain your brai...,91
246,YouTube,XtnNpUyK3KM,https://www.youtube.com/watch?v=XtnNpUyK3KM,Live The Life You Love--Neuro-Enhancement Stra...,Information video on Neuro-Enhancement Strateg...,J Schoener,NaN,1391.0,0.0,0.0,nootropics,unknown,2010-05-03,False,Live The Life You Love--Neuro-Enhancement Stra...,live the life you love neuro enhancement stra...,91
312,YouTube,8fwgr1M0GX4,https://www.youtube.com/watch?v=8fwgr1M0GX4,Neurofeedback Therapy: Anxiety &amp; Panic Dis...,Please visit this site: www.neurofeedbackbook....,C Albright,NaN,18482.0,50.0,0.0,nootropics,en,2010-06-03,False,Neurofeedback Therapy: Anxiety &amp; Panic Dis...,neurofeedback therapy anxiety amp panic dis...,91
449,YouTube,jjY9ILDDOaM,https://www.youtube.com/watch?v=jjY9ILDDOaM,Depression and Neurofeedback,DoctorClarity's shared video file.,C Albright,this video will make you depressed || The musi...,4567.0,8.0,6.0,nootropics,unknown,2010-07-28,False,Depression and Neurofeedback. DoctorClarity's ...,depression and neurofeedback doctorclarity s ...,91

This video talks about the neuroscience

In [25]:
#topic number 104
df[df['topic']==104]

,source,video_id,video_url,title,description,channel,comments,views,likes,comments_count,keywords,country,date,likes_missing,text,clean_text,topic
10469,YouTube,orioiI25J2w,https://www.youtube.com/watch?v=orioiI25J2w,BBCA Social Ad | Pause Well-Aging - Comedic Cl...,NaN,Base Beauty Creative Agency,NaN,276.0,2.0,0.0,well aging,en,2021-03-10,False,BBCA Social Ad | Pause Well-Aging - Comedic Cl...,bbca social ad pause well aging comedic clip,104
10472,YouTube,hpDWWYGhWZE,https://www.youtube.com/watch?v=hpDWWYGhWZE,BBCA Social Ad | Pause Well-Aging - Comedic Cl...,NaN,Base Beauty Creative Agency,NaN,325.0,2.0,0.0,well aging,en,2021-03-10,False,BBCA Social Ad | Pause Well-Aging - Comedic Cl...,bbca social ad pause well aging comedic clip,104
10473,YouTube,Q4Ay77IiTC8,https://www.youtube.com/watch?v=Q4Ay77IiTC8,BBCA Social Ad | Pause-Well Aging - Comedy Clip 6,NaN,Base Beauty Creative Agency,NaN,42.0,0.0,0.0,well aging,en,2021-03-10,False,BBCA Social Ad | Pause-Well Aging - Comedy Cli...,bbca social ad pause well aging comedy clip,104
10475,YouTube,MuS_0eiy--Y,https://www.youtube.com/watch?v=MuS_0eiy--Y,BBCA Social Ad | Pause Well-Aging - Comedic Cl...,NaN,Base Beauty Creative Agency,NaN,32.0,0.0,0.0,well aging,en,2021-03-10,False,BBCA Social Ad | Pause Well-Aging - Comedic Cl...,bbca social ad pause well aging comedic clip,104
10476,YouTube,4gl0NcvyS4c,https://www.youtube.com/watch?v=4gl0NcvyS4c,BBCA Social Ad | Pause-Well Aging - Comedy Clip 4,NaN,Base Beauty Creative Agency,NaN,77.0,0.0,0.0,well aging,en,2021-03-10,False,BBCA Social Ad | Pause-Well Aging - Comedy Cli...,bbca social ad pause well aging comedy clip,104
13456,YouTube,Vqf_4yPV4Yw,https://www.youtube.com/watch?v=Vqf_4yPV4Yw,⏰Has Jane Fonda Aged Well? (Surgeon Reacts),Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,Nope still a traitor. || Beautiful || She look...,41813.0,1057.0,67.0,well aging,en-US,2024-04-22,False,⏰Has Jane Fonda Aged Well? (Surgeon Reacts). D...,has jane fonda aged well surgeon reacts do...,104
13474,YouTube,hD2bikurgJ8,https://www.youtube.com/watch?v=hD2bikurgJ8,Has Dolly Parton Aged Well? (Surgeon Reacts),Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,😂😂😂how on earth that ppl think she aged well??...,10461.0,362.0,18.0,well aging,en-US,2024-04-29,False,Has Dolly Parton Aged Well? (Surgeon Reacts). ...,has dolly parton aged well surgeon reacts ...,104
13507,YouTube,IVBi91HFIDU,https://www.youtube.com/watch?v=IVBi91HFIDU,⏰ Has Meg Ryan Aged Well? (Surgeon Reacts),Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,She doesn&#39;t look like herself || I&#39;m s...,22225.0,522.0,22.0,well aging,en-US,2024-05-13,False,⏰ Has Meg Ryan Aged Well? (Surgeon Reacts). Do...,has meg ryan aged well surgeon reacts doub...,104
13520,YouTube,K27sG5cWkZc,https://www.youtube.com/watch?v=K27sG5cWkZc,⏰ Has Simon Cowell Aged Well? (Surgeon Reacts),Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,It&#39;s a no from me. || Let me just say this...,41371.0,686.0,76.0,well aging,en-US,2024-05-20,False,⏰ Has Simon Cowell Aged Well? (Surgeon Reacts)...,has simon cowell aged well surgeon reacts ...,104
13579,YouTube,gT4udUrXdec,https://www.youtube.com/watch?v=gT4udUrXdec,⏰ Has Courteney Cox Aged Well? (Surgeon Reacts),Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,She should cut her hair. Long dark hair often ...,103879.0,2094.0,103.0,well aging,en-US,2024-06-13,False,⏰ Has Courteney Cox Aged Well? (Surgeon Reacts...,has courteney cox aged well surgeon reacts ...,104
13587,YouTube,6QG4xVwq_2U,https://www.youtube.com/watch?v=6QG4xVwq_2U,⏰ Has Kyle Richard’s Aged Well? (Surgeon Reacts),Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,her whole face shape constantly changes back a...,16199.0,245.0,7.0,well aging,en-US,2024-06-17,False,⏰ Has Kyle Richard’s Aged Well? (Surgeon React...,has kyle richard s aged well surgeon reacts ...,104
13607,YouTube,w3sKecJW6Y0,https://www.youtube.com/watch?v=w3sKecJW6Y0,⏰ Has Jennifer Aniston Aged Well? (Surgeon Rea...,Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,She is NOT aging well due to all the fillers.....,23260.0,441.0,32.0,well aging,en-US,2024-06-24,False,⏰ Has Jennifer Aniston Aged Well? (Surgeon Rea...,has jennifer aniston aged well surgeon react...,104
13622,YouTube,6VYA_QlBphs,https://www.youtube.com/watch?v=6VYA_QlBphs,⏰ Has Cindy Crawford Aged Well? (Surgeon Reacts),Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,Do you really think there is a surgeon brave e...,45873.0,1652.0,89.0,well aging,en-US,2024-07-01,False,⏰ Has Cindy Crawford Aged Well? (Surgeon React...,has cindy crawford aged well surgeon reacts ...,104
13639,YouTube,BRhb4c2vgtA,https://www.youtube.com/watch?v=BRhb4c2vgtA,⏰ Has Madonna Aged Well? (Surgeon Reacts),Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,I dont recognise the newer version. || Reminds...,100721.0,2028.0,215.0,well aging,en-US,2024-07-08,False,⏰ Has Madonna Aged Well? (Surgeon Reacts). Dou...,has madonna aged well surgeon reacts doubl...,104
13664,YouTube,NJGWaSxg-MY,https://www.youtube.com/watch?v=NJGWaSxg-MY,⏰ Has Pamela Anderson Aged Well? (Surgeon Reacts),Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,Nose job and facelift it’s so obvious people!!...,57882.0,1837.0,113.0,well aging,en-US,2024-07-15,False,⏰ Has Pamela Anderson Aged Well? (Surgeon Reac...,has pamela anderson aged well surgeon reacts...,104
13678,YouTube,9LU7NxWyMfw,https://www.youtube.com/watch?v=9LU7NxWyMfw,⏰ Has Hugh Jackman Aged Well? (Surgeon Reacts),Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,He looks good but had some work done. || why d...,14685.0,528.0,14.0,well aging,en-US,2024-07-22,False,⏰ Has Hugh Jackman Aged Well? (Surgeon Reacts)...,has hugh jackman aged well surgeon reacts ...,104
13698,YouTube,E5wpGCSu0YA,https://www.youtube.com/watch?v=E5wpGCSu0YA,⏰ Has Erika Jayne Aged Well? (Surgeon Reacts),Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,This is all too confusing.... || She’s definit...,16844.0,368.0,17.0,well aging,en-US,2024-07-29,False,⏰ Has Erika Jayne Aged Well? (Surgeon Reacts)....,has erika jayne aged well surgeon reacts d...,104
13714,YouTube,uSMoeh7JZkc,https://www.youtube.com/watch?v=uSMoeh7JZkc,⏰Has Gisele Bündchen Aged Well? (Surgeon Reacts),Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,Mulher Brasileira da de dez em qualquer outra ...,22035.0,445.0,10.0,well aging,en-US,2024-08-05,False,⏰Has Gisele Bündchen Aged Well? (Surgeon React...,has gisele b ndchen aged well surgeon reacts...,104
13746,YouTube,7xHBtULXSIE,https://www.youtube.com/watch?v=7xHBtULXSIE,⏰Has Christie Brinkley Aged Well? (Surgeon Rea...,Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,Whatever she has or hasn&#39;t had done is her...,26958.0,840.0,83.0,well aging,en-US,2024-08-19,False,⏰Has Christie Brinkley Aged Well? (Surgeon Rea...,has christie brinkley aged well surgeon reac...,104
13759,YouTube,c1CNMxiC7sk,https://www.youtube.com/watch?v=c1CNMxiC7sk,⏰ Has Gwyneth Paltrow Aged Well? (Surgeon Reacts),Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,Nope || She looks exhausted from 40’s on.<br>S...,12813.0,379.0,21.0,well aging,en-US,2024-08-26,False,⏰ Has Gwyneth Paltrow Aged Well? (Surgeon Reac...,has gwyneth paltrow aged well surgeon reacts...,104
13808,YouTube,MczFpOLauYQ,https://www.youtube.com/watch?v=MczFpOLauYQ,⏰ Has Demi Moore Aged Well? (Surgeon Reacts),Double Board Certified Plastic Surgeon Reviews...,Tansavatdi Facial Plastic Surgery,She was beautiful when she reached 52. Whoever...,25858.0,550.0,43.0,well aging,en-US,2024-09-09,False,⏰ Has Demi Moore Aged Well? (Surgeon Reacts). ...,has demi moore aged well surgeon reacts do...,104

It contains the some suspicious vidoes. However, the half of the vidoes are about whether the specific celecbrity aged well or not. It might be related. Because it might contain discussion about  people's perception of well aging

In summary, we can say that every topic was more or less related

In [26]:
import pandas as pd

df.to_csv("./topics_2/topics/data.csv", index=False)
tp.to_csv("./topics_2/topics/mpnet_topics.csv", index=False)

<h1> Next steps</h1>

**Next steps for the bertopic analysis**
- Try to deal with the noisy topics (later)