# Library Inclusion and Utilities

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from NLP import *
from itables import show
import itables.options as opt

/home/iskender/anaconda3/envs/bertopic-env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

show(tag_clean_df[['section','headline','trailText', 'tags']], scrollY="500px", scrollCollapse=True)

# Sanity Check

## Ageing-only corpus

In [42]:
topic_model, topic_info, g_no_longevity_out = analyze_bertopic(g_no_longevity, v_min_df=1, v_max_df=0.5,text_col="bodyText",top_n_words=30,
                                     save_csv=None)

2025-08-20 22:26:48,771 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████████████████████████████| 33/33 [05:59<00:00, 10.91s/it]
2025-08-20 22:32:48,826 - BERTopic - Embedding - Completed ✓
2025-08-20 22:32:48,826 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-08-20 22:32:49,758 - BERTopic - Dimensionality - Completed ✓
2025-08-20 22:32:49,759 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-08-20 22:32:49,797 - BERTopic - Cluster - Completed ✓
2025-08-20 22:32:49,799 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-08-20 22:32:51,189 - BERTopic - Representation - Completed ✓

In [43]:
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,222,-1_hiv_prison_coal_carbon,"[hiv, prison, coal, carbon, gaba, mushrooms, p...","[On an August morning in 2008, Tony Wyss-Coray..."
1,0,247,0_beauty_skincare_botox_makeup,"[beauty, skincare, botox, makeup, serum, cosme...",[1 Garnier Ambre Solaire Sensitive Face Fluid ...
2,1,81,1_fertility_migration_retirement age_older wor...,"[fertility, migration, retirement age, older w...","[People are a good thing, the most precious re..."
3,2,73,2_beds_term conditions_ambulance_commissioning,"[beds, term conditions, ambulance, commissioni...","[Displayed, not particularly prominently, on a..."
4,3,53,3_mice_stem cells_stem cell_gene,"[mice, stem cells, stem cell, gene, senescent,...",[Scientists have slowed down the ageing proces...
5,4,53,4_loneliness_calment_zak_divorce,"[loneliness, calment, zak, divorce, marsh, jea...","[Human societies, at all times and places, hav..."
6,5,50,5_prostate_lung_prostate cancer_cancer research,"[prostate, lung, prostate cancer, cancer resea...","[Survival rates for some types of cancer, incl..."
7,6,47,6_intuition_ear_alzheimer disease_people dementia,"[intuition, ear, alzheimer disease, people dem...","[Slow down, that used to be the mantra for mid..."
8,7,43,7_baker_aged care_care homes_rent,"[baker, aged care, care homes, rent, dilnot, b...",[A major shift in Tory housing policy in favou...
9,8,38,8_pollution_air pollution_cough_asthma,"[pollution, air pollution, cough, asthma, balm...",[Young Britons are dying from asthma at a high...
10,9,33,9_public sector_unions_union_strike,"[public sector, unions, union, strike, hutton,...",[R ubbish swirls through Southampton's shoppin...
11,10,24,10_biological age_horvath_epigenetic_kenyon,"[biological age, horvath, epigenetic, kenyon, ...",[Tech entrepreneur Bryan Johnson is talking ab...
12,11,18,11_fasting_portions_carb_dopamine,"[fasting, portions, carb, dopamine, veg, nuts,...","[Like everyone else in the world, my blood ran..."
13,12,17,12_funeral_palliative_lobban_palliative care,"[funeral, palliative, lobban, palliative care,...",[Dr BJ (Bruce) Miller is convinced that how we...
14,13,17,13_superannuation_state pension_pension age_in...,"[superannuation, state pension, pension age, i...",[Emily Millane – Per Capita On the train tonig...
15,14,14,14_venom_dom_citizen science_snakes,"[venom, dom, citizen science, snakes, citizen,...",[Today we celebrate the 350th anniversary of t...
16,15,14,15_menopause_oestrogen_fertility_vaginal,"[menopause, oestrogen, fertility, vaginal, uti...","[For my birthday last week, the algorithm gave..."
17,16,12,16_optimists_sonneberg_new optimists_boars,"[optimists, sonneberg, new optimists, boars, s...",[Under the bright lights of Berlin's inner cit...

In [32]:
full_keyword_getter(guardian_base_out)

-1.0 → ['discrimination', 'menopause', 'japan', 'older women', 'anger', 'dating', 'dancing', 'glasses', 'writers', 'pension', 'age uk', 'midlife crisis', '101', 'expectancy', 'life expectancy', 'bus', 'mothers', 'social care', 'workplace', 'ageing population', 'fat', 'winter', 'care homes', 'drugs', 'baby boomers', 'volunteering', 'hospitals', 'mr', 'edith', 'incontinence']
0.0 → ['cells', 'mice', 'drug', 'diseases', 'lifespan', 'biological', 'drugs', 'animals', 'cell', 'telomeres', 'senescent', 'factors', 'genes', 'gene', 'immune', 'genetic', 'scientific', 'senescent cells', 'ageing process', 'brains', 'age related', 'dna', 'trials', 'plasma', 'treatments', 'life expectancy', 'expectancy', 'biological age', 'stem', 'anti ageing']
1.0 → ['pension', 'expectancy', 'life expectancy', 'pensions', 'state pension', 'economy', 'poverty', 'employment', 'retirement age', 'pensioners', 'pension age', 'wealth', 'workforce', 'employers', 'fertility', 'statistics', 'inequality', 'rent', 'cohousing', 'harper', 'retirees', 'baby boomers', 'savings', 'older workers', 'healthy life', 'policies', 'ageing population', 'welfare', 'projected', 'sector']
2.0 → ['happiness', 'dull', 'millennials', 'boomer', 'adulthood', 'granny', 'ageist', 'partridge', 'older women', 'amis', 'alan', 'tom', 'pause', 'midlife crisis', 'graham', 'unhappy', 'boredom', 'pleasures', 'tomorrow', 'centenarians', 'satisfaction', 'remarks', 'psychology', 'lively', 'optimistic', 'gen', 'mature', 'grannies', 'stereotypes', 'bus']
3.0 → ['collagen', 'cosmetic', 'wrinkles', 'botox', 'anti ageing', 'cream', 'skincare', 'sun', 'serum', 'models', 'makeup', 'cells', 'brands', 'procedures', 'facial', 'older women', 'vitamin', 'product', 'filler', 'acid', 'ingredients', 'sunscreen', 'nirdosh', 'treatments', 'clothes', 'moisturiser', 'faces', 'creams', 'uv', 'grey hair']
4.0 → ['guardian letters', 'guardian readers', 'edition', 'print edition', 'click upload', 'readers click', 'share guardian', 'upload', 'like share', 'yorkshire', 'boris', 'kent', 'boris johnson', 'sussex', 'click visit', 'debate email', 'join debate', 'letters click', 'email guardian', 'com read', 'visit gu', 'letters theguardian', 'gu', 'com letters', 'gu com', 'theguardian', 'theguardian com', 'letters spread', 'publish best', 'submissions letters']
5.0 → ['aged care', 'social care', 'care homes', 'commission', 'providers', 'royal commission', 'residential', 'sector', 'resident', 'nurses', 'australians', 'nursing home', 'care services', 'staffing', 'councils', 'home care', 'health social', 'care quality', 'facility', 'providing', 'residential aged', 'adult social', 'age uk', 'nursing homes', 'care sector', 'remote', 'ratios', 'standards', 'unpaid', 'provider']
6.0 → ['muscle', 'shoulder', 'grip', 'sport', 'gym', 'muscles', 'sports', 'tennis', 'marathon', 'knee', 'arms', 'athletes', 'football', 'strength training', 'weights', 'swimming', 'pavey', 'movements', 'macdonald', 'trainer', 'swim', 'coach', 'intensity', 'leg', 'workouts', 'exercises', 'squat', 'heel', 'injury', 'cycling']
7.0 → ['end life', 'palliative', 'palliative care', 'suicide', 'assisted', 'life care', 'assisted dying', 'terminal', 'funeral', 'mavani', 'euthanasia', 'oregon', 'cemetery', 'burial', 'oncologist', 'terminally ill', 'assisted suicide', 'terminally', 'complications', 'elderly patients', 'impaired', 'hospitals', 'advance', 'tender', 'catholic', 'buried', 'insurance', 'aid', 'nursing home', 'hospice']
8.0 → ['chemirmir', 'grandad', 'eribon', 'conflict', 'assisted', 'anger', 'funeral', 'john campaign', 'mom', 'grieving', 'apartment', 'shanti', 'ashes', 'assisted dying', 'aunt', 'chase', 'texas', 'nursing home', 'cleaning', 'aged care', 'mourning', 'abandoned', 'items', 'uncle', 'guilty', 'gifts', 'ice cream', 'new life', 'prison', 'visitor']
9.0 → ['friendships', 'friendship', 'isolation', 'cities', 'lesley', 'romantic', 'social isolation', 'old friends', 'epidemic', 'solitude', 'age uk', 'poor health', 'widowed', 'close friends', 'dating', 'circles', 'boyfriend', 'volunteer', 'zoom', 'divorced', 'corner', 'connect', 'willett', 'independent age', 'socialising', 'councils', 'sharing', 'million people', 'acute', 'monthly']
10.0 → ['menopause', 'hrt', 'fertility', 'testosterone', 'symptoms', 'breast', 'osteoporosis', 'bone', 'breast cancer', 'oestrogen', 'menopausal', 'low testosterone', 'pregnancy', 'perimenopause', 'gp', 'hormone', 'women health', 'pills', 'bones', 'eggs', 'density', 'hormones', 'motherhood', 'replacement', 'frozen', 'hormonal', 'inquiry', 'gps', 'pregnant', 'increased risk']
11.0 → ['robot', 'digital', 'robots', 'tech', 'seniors', 'cash', 'sensors', 'climate', 'watson', 'startup', 'smartphone', 'banking', 'virtual', 'users', 'companion', 'robotic', 'conspiracy', 'parenting', 'honoré', 'mobile', 'device', 'tablet', 'smartphones', 'hub', 'san', 'technologies', 'apps', 'ai', 'francisco', 'san francisco']
12.0 → ['actors', 'aaron', 'rossellini', 'zeldin', 'actor', 'films', 'adams', 'nina', 'drama', 'gay', 'comedy', 'audience', 'beckett', 'acting', 'lake', 'hollywood', 'italy', 'oscar', 'production', 'characters', 'italian', 'actress', 'philip', 'scenes', 'directors', 'opera', 'jack', 'creativity', 'daniel', 'celebrity']
13.0 → ['nichols', 'films', 'stars', 'characters', 'cathy', 'actor', 'actors', 'bachelor', 'drama', 'ladies', 'hollywood', 'acting', 'older female', 'cast', 'cinema', 'seasons', 'aged women', 'turner', 'movies', 'bell', 'season', 'kelly', 'representation', 'oscar', 'older women', 'cox', 'ambition', 'actress', 'comedy', 'award']
14.0 → ['sex life', 'sexually', 'pamela', 'intimacy', 'sex lives', 'anonymous', 'sexuality', 'older men', 'pleasure', 'dating', 'topics', 'couples', 'libido', 'description', 'lee', 'appearing', 'submissions', 'desires', 'erotic', 'stuart', 'graham', 'psychotherapist', 'sensation', 'delay', 'treating', 'positions', 'theguardian', 'theguardian com', 'sexy', 'regrets']
15.0 → ['mick', 'beatles', 'band', 'mccartney', 'song', 'jagger', 'fans', 'singing', 'musicians', 'tour', 'rolling', 'harris', 'audience', 'guitar', 'fame', 'musical', 'performers', 'bob', 'levy', 'gay', 'touring', 'burn', 'guys', 'tiktok', 'roll', 'bands', 'crowd', 'cook', '52', 'grow old']
16.0 → ['calment', 'zak', 'frank', 'eddie', 'sue', 'jeanne', 'mosse', 'yvonne', 'novels', 'nelson', 'olivier', 'jeanne calment', 'investigation', 'russian', 'kramer', 'graham', 'james', 'dna', 'portraits', 'theory', 'fiction', 'memoir', 'gerontology', 'paris', 'images', 'portrait', 'painting', 'backdrop', 'supercentenarians', 'historical']
17.0 → ['dancing', 'dalman', 'ballet', 'dancers', 'moves', 'adelaide', 'bending', 'thompson', 'hughes', 'dancer', 'flight', 'contemporary', 'split', 'kramer', 'performing', 'classical', 'instructor', 'arts', 'flying', 'mature', 'olympic', 'artistic', 'creativity', 'shed', 'sport', 'flexibility', 'gym', 'paris', 'tour', 'performances']
18.0 → ['biden', 'trump', 'senate', 'joe biden', 'republican', 'senator', 'election', 'mcconnell', 'democratic', 'leaders', 'donald', 'democrats', 'presidential', 'donald trump', 'leader', 'elected', 'congress', 'candidates', 'voters', 'politicians', 'obama', 'generational', 'vote', '2024', 'leadership', 'new generation', 'polls', 'average age', 'speaker', 'united states']
19.0 → ['napping', 'insomnia', 'daytime', 'asleep', 'awake', 'bedtime', 'nap', 'timing', 'night sleep', 'naps', 'waking', 'volume', 'woke', 'females', 'foster', 'noise', 'slept', 'patterns', 'habits', 'caffeine', 'adolescence', 'alzheimer disease', 'previous research', 'males', 'puberty', 'genetic', 'occurs', 'cognitive decline', 'cognitive impairment', 'brain health']
20.0 → ['drivers', 'older drivers', 'driver', 'licence', 'mandatory', 'crash', 'roads', 'assessment', 'newton', 'vehicle', 'premium', 'wheel', 'victoria', 'fatal', 'victorian', 'accidents', 'insurance', 'safely', 'injuries', 'assessments', 'motor', 'ice cream', 'injury', 'reactions', 'keys', 'involving', 'transport', '97', 'ice', 'independence']

## Across-tags corpus by core keys

In [38]:
g = pd.read_csv("../GuardianAPI/guardian_base_across_tags.csv")
g_age_only = pd.read_csv('../GuardianAPI/guardian_ageing_tag_only.csv')
g_no_longevity = pd.read_csv('../GuardianAPI/guardian_base_across_tags_wo_longevity.csv')

In [39]:
g = clean_sections(g,[])
g_age_only = clean_sections(g_age_only,[])
g_no_longevity = clean_sections(g_no_longevity,[])

The dataset shrinked from 4499 to 1811
The dataset shrinked from 1479 to 1124
The dataset shrinked from 1650 to 1056

In [5]:
g.groupby("section")['id'].count()

section
Business                             98
Education                            18
Environment                         114
Fashion                             200
Food                                 60
Healthcare Professionals Network     12
Inequality                            6
Life and style                      366
News                                 28
Opinion                             434
Science                             161
Society                             280
Wellness                             34
Name: id, dtype: int64

In [33]:
show(g[['section','headline','trailText', 'tags']], scrollY="500px", scrollCollapse=True)

In [7]:
g = pd.concat([g,g_age_only])

In [8]:
g.drop_duplicates(subset="id",inplace=True)

In [25]:
check = g_age_only_out[~g_age_only_out['id'].isin(g['id'])]

In [26]:
check

,id,section,pub_date,web_url,headline,trailText,byline,wordcount,bodyText,links,authors,tags,topic,topic_prob,topic_keywords
0,lifeandstyle/2017/dec/03/age-old-problem-how-t...,Life and style,2017-12-03T06:00:33Z,https://www.theguardian.com/lifeandstyle/2017/...,Age old problem: how to stay clever for longer,There are ways to ward off dementia and the il...,NaN,590,"Sorry to break it to you, but there’s bad news...",https://www.guardianbookshop.com/how-much-brai...,NaN,Ageing; Health & wellbeing; Dementia; Life and...,0.0,1.000000,"[cells, mice, drug, animals, cell, lifespan, s..."
1,commentisfree/2017/sep/22/older-workers-new-sk...,Opinion,2017-09-22T05:00:38Z,https://www.theguardian.com/commentisfree/2017...,"Yes, older workers need new skills – but they ...",The BBC’s plan to have millennials ‘reverse me...,Gaby Hinsliff,1079,"Old dogs, meet new tricks. The BBC’s director ...",http://www.telegraph.co.uk/news/2017/09/21/bbc...,Gaby Hinsliff,Work & careers; BBC; James Purnell; Ageing; Me...,12.0,1.000000,"[leaders, biden, vote, boomer, june, senator, ..."
2,science/head-quarters/2017/oct/31/the-reminisc...,Science,2017-10-31T12:00:25Z,https://www.theguardian.com/science/head-quart...,The reminiscence bump: why America’s greatest ...,We tend to recall more memories from our youth...,Matthew Warren,977,"In 2016, as Donald Trump was busy securing the...",https://www.nytimes.com/2016/04/26/upshot/when...,NaN,Science; Psychology; Memory; Trump administrat...,4.0,0.360162,"[calment, zak, happiness, jeanne, 101, yvonne,..."
5,commentisfree/2018/may/10/cure-baldness-hairle...,Opinion,2018-05-10T08:00:07Z,https://www.theguardian.com/commentisfree/2018...,They can keep their ‘cure’ for baldness. I lov...,"When I started losing my long, obsidian, Linki...",Tom Usher,675,In news that will be mostly of no use to anyon...,http://www.bbc.co.uk/news/health-44038756; htt...,Tom Usher,Men's hair; Beauty; Life and style; Fashion; M...,1.0,0.421015,"[collagen, cosmetic, wrinkles, botox, appearan..."
8,society/2018/jun/07/army-veteran-sleeps-in-she...,Society,2018-06-07T14:40:27Z,https://www.theguardian.com/society/2018/jun/0...,Army veteran sleeps in shed after being made h...,Tony Squirrell said he’d rather bed down in al...,Steven Morris and agency,682,An army veteran has been sleeping in his allot...,https://www.theguardian.com/commentisfree/2018...,Steven Morris,Housing; Welfare; UK news; Homelessness; Socie...,2.0,0.280937,"[aged care, care homes, carers, providers, com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1469,lifeandstyle/2025/may/16/i-want-a-relationship...,Life and style,2025-05-16T00:35:47Z,https://www.theguardian.com/lifeandstyle/2025/...,"I want a relationship, not out of love or pass...",Lots of the reasons we want a relationship boi...,Eleanor Gordon-Smith,720,I’ve come to a moment in my life I never expec...,https://www.theguardian.com/lifeandstyle/2025/...,Eleanor Gordon-Smith,Relationships; Life and style; Australian life...,9.0,0.068110,"[lonely, friendships, friendship, lesley, isol..."
1470,society/2025/may/25/labours-u-turn-on-winter-f...,Society,2025-05-25T16:22:51Z,https://www.theguardian.com/society/2025/may/2...,Labour’s U-turn on winter fuel cuts is too lit...,Letters: <strong>Ian Jenkinson</strong> says v...,NaN,559,"While Keir Starmer’s U-turn is welcome, it’s p...",https://www.theguardian.com/society/2025/may/2...,NaN,Benefits; Labour; Keir Starmer; Rachel Reeves;...,-1.0,0.031385,"[fertility, drivers, menopause, discrimination..."
1472,lifeandstyle/2025/jul/14/no-age-isnt-just-a-nu...,Life and style,2025-07-14T10:00:06Z,https://www.theguardian.com/lifeandstyle/2025/...,"No, age isn’t just a number – and the sooner w...",It’s tempting to want to stay young for ever. ...,Moya Sarner,922,"Sitting in a cafe recently, I saw a poster adv...",https://www.theguardian.com/lifeandstyle/2025/...,Moya Sarner,Mental health; Health & wellbeing; Counselling...,4.0,0.164591,"[calment, zak, happiness, jeanne, 101, yvonne,..."
1476,commentisfree/2025/jul/27/gen-z-stare-its-got-...,Opinion,2025-07-27T13:00:22Z,https://www.theguardian.com/commentisfree/2025...,Have you been a victim of the ‘gen Z stare’? I...,Those aged between 13 and 28 have been accused...,Emma Beddington,779,Have you been the victim of a gen Z stare? May...,https://www.bbc.co.uk/bitesize/articles/zf8kfd...,Emma Beddington,Society; Ageing; Young people; Social etiquett...,13.0,1.000000,"[dull, granny, dull men, ageist, millennials, ..."
1477,wellness/2025/jul/25/older-women-weightlifting,Wellness,2025-07-25T16:00:28Z,https://www.theguardian.com/wellness/2025/jul/...,‘Old people are capable of more’: meet the fem...,Forget the stereotype of the frail old woman w...,Madeleine Aggeler,1074,Joan MacDonald is an influencer. There’s no ot...,https://www.instagram.com/p/CxgCBo0OK6M/; http...,Madeleine Aggeler,Well actually; Weightlifting; Fitness; Sport; ...,5.0,0.454166,"[muscle, shoulder, grip, sport, muscles, secon..."

In [37]:
show(g_out[g_out['topic']==28][['section','headline','trailText', 'tags']], scrollY="500px", scrollCollapse=True)

In [3]:
nyt = pd.read_csv('../NYT/Data_NYT/nyt_healthy_ageing_2010_present.csv')

EmptyDataError: No columns to parse from file

In [4]:
er = pd.read_csv("../newsapi.ai/core_keys_data.csv")

In [9]:
er

,title,body,url,source,pub_datetime,lang
0,Does Coffee Fight Ageing?,If you've ever sipped your morning coffee wond...,https://indianf.com/coffee-and-healthy-ageing-...,Indian Flash,2025-08-16 11:44:04+00:00,eng
1,Himax Subsidiary Liqxtal Proprietary Vision-Ca...,Presented at Taiwan Healthy Ageing Tech Show i...,https://www.itnewsonline.com/GlobeNewswire/Him...,IT News Online,2025-07-29 08:38:21+00:00,eng
2,Himax Subsidiary Liqxtal Proprietary Vision-Ca...,Man Group PLC : Form 8.3 - American Axle & Man...,https://www.manilatimes.net/2025/07/29/tmt-new...,The Manila times,2025-07-29 07:21:40+00:00,eng
3,Himax Subsidiary Liqxtal Proprietary Vision-Ca...,Presented at Taiwan Healthy Ageing Tech Show i...,https://taiwannews.com.tw/en/news/6166359,Taiwan News,2025-07-29 07:24:41+00:00,eng
4,World Senior Citizens Day 2025: What doctors w...,"Growing old isn't easy, but doctors say ageing...",https://www.financialexpress.com/life/health/w...,The Financial Express,2025-08-21 05:54:33+00:00,eng
...,...,...,...,...,...,...
4295,MOUNT DOOM: SATANIC AI & THE BATTLE FOR YOUR S...,Paul List the author of Mount Doom: The Prophe...,https://www.sgtreport.com/2025/07/mount-doom-s...,SGT Report,2025-07-24 03:16:41+00:00,eng
4296,Heidi Klum's New $19 Erewhon Smoothie Is a Run...,A portion of proceeds benefits Children's Hosp...,https://people.com/heidi-klum-launches-erewhon...,PEOPLE.com,2025-07-23 12:00:00+00:00,eng
4297,Mud/Wtr expands functional F&B portfolio with ...,Mud/Wtr expands functional F&B portfolio with ...,https://www.foodbev.com/news/mud-wtr-expands-f...,FoodBev Media,2025-07-22 12:44:07+00:00,eng
4298,Why men are quietly spending big on wellness boom,Gen Z and millennial men are driving unprecede...,https://rollingout.com/2025/07/21/men-quietly-...,Rolling Out,2025-07-21 14:54:32+00:00,eng
4299,"SIRO uses a game-changing approach to sleep, r...",As wellness evolves beyond spa treatments and ...,https://emirateswoman.com/how-dubais-siro-uses...,Emirates Woman,2025-07-21 09:24:07+00:00,eng

In [8]:
er['pub_datetime'] = pd.to_datetime(er['pub_datetime'], errors='coerce')

In [15]:
er['pub_datetime'].dt.month.unique()

array([8, 7], dtype=int32)

In [3]:
voa_df = pd.read_csv("../VOA/longevity_data.csv")

/tmp/ipykernel_5324/3286909818.py:1: DtypeWarning: Columns (25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63) have mixed types. Specify dtype option on import or set low_memory=False.
  voa_df = pd.read_csv("../VOA/longevity_data.csv")

In [8]:
pd.set_option('display.max_colwidth',None)
voa_df['paragraphs']

0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ['President Barack Obama took time at the end of a busy week Friday to cite what he says is enormous progress in repairing the U.S. economy.\xa0 The president faces ongoing criticism of his policies from opposition Republicans.', 'The most significant legislative accomplishment for the president and majority Democrats since the historic health care overhaul achieved earlier this year, is the financial regulatory reform bill Mr. Obama signed on Thursday.', 'It is the outcome of almost two years of intense debate on Capitol Hill concerning the best ways to respond to excesses on Wall Street, protect consumers, and avoid another financial system collapse.', 'Speaking in the White House Roosevelt Room, the president said the new law will protect consumers and the economy from recklessness and irresponsibility that led to the worst financial breakdown since the Great Depression.', '"It\'s a reform that will help us put a stop to the abusive practices of mortgage lenders and credit card companies and ensure that people get the straight, unvarnished information that they need before they take out a loan or open a credit card," he said. "It will bring the shadowy deals that caused the financial crisis into the light of day, and it will end taxpayer bailouts of Wall Street firms and give shareholders a say on executive compensation."', 'To underscore his points, the president referred to a new report by Ken Feinberg, who Mr. Obama appointed to oversee compensation issues.\xa0 The report said 17 banks gave top executives $1.6 billion in bonuses while they were receiving billions of dollars in government bailout funds.', 'The president pointed to two other achievements - a six-month extension of emergency government benefits for people out of work, and an initiative to reduce waste in government.', 'Mr. Obama pressed for Senate action on another piece of legislation; tax incentives and lending for small businesses.\xa0 And he sounded a theme he will use as he campaigns for Democratic candidates before the November mid-term congressional elections.', '"The folks who I have met with across this country, they cannot afford any more political games," he said.\xa0 "They need us to do what they sent us here to do.\xa0 They didn\'t send us here to wage a never-ending campaign; they didn\'t send us here to do what is best for our political party.\xa0 They sent us here to do what is best for the United States of America and all our citizens, whether Democrats or Republicans or Independents.\xa0 In other words, they sent us here to govern."', "As the president spotlights achievements, Republicans continue to criticize him on virtually every one of his policies.\xa0 Indiana Republican Mike Pence asserted that President Obama's policies and those of Democrats will lead to huge tax increases.", '"As we have done on their failed stimulus policy, as we have did on their national energy tax, as we did on their government take over of health care, House Republicans will stand in the gap to protect taxpayers from the largest tax increase in American history," he said.', 'Democratic leaders meanwhile cited Republican opposition as they acknowledged they had given up on passing comprehensive clean energy/climate change legislation before the August recess.', 'Senate Majority Leader Harry Reid said "Unfortunately this time we don\'t have a single Republican to work with in achieving this goal," Reid said.\xa0 "For me, it is terribly disappointing."', '"We will continue to work with the senators to craft important, comprehensive legislation," said Carol Browner, Director of the White House Office on Energy and Climate Change Policy.', 'Having accomplished the bulk of the pre-congressional recess agenda, the president will increasingly focus on the November congressional elections, campaigning for Democrats and pressing his messages about economic recovery.', 'The White House announced he will travel to New Jersey next week, a state that remains strongly Democratic.\xa0 The unemployment rate there is about 9.6 percent, slightly more than the national level.', "Also announced, presidential visits next week and in early August to Chrysler, General Motors and Ford automobile plants in Michigan and Chicago, Illinois. The White House says these will highlight a U.S. auto industry that is strengthening as a result of the president's actions to save it."]
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ["Southern Sudan expects to become Africa?s newest nation after the results of this month?s independence referendum are officially released February 7.\xa0 Building the new nation will not be easy.\xa0 Years of neglect and civil war virtually destroyed the region's infrastructure and social services, including its prison system.", 'It is morning inspection at Juba Prison, the largest of southern Sudan?s 10 prisons. About 900 men, women and children are incarcerated in a facility built to hold 600.', 'Director of Prisons Lieutenant General Abel Makoi Wol is trying to rebuild and reform a penal system that virtually collapsed during the decades of conflict with the government in Khartoum.', '"Nothing was existing because most of the prisons fell [collapsed] during the war," said Wol. "And people started renovating the old ones which were actually built in the colonial era.\xa0 And they did not have any structures available."', 'Wol says many prisoners have yet to be tried.\xa0 Others have served their sentences, but have not been released.\xa0 This is because of inefficient courts, prosecutors and police, another legacy of the war.', 'More than 10 juveniles are also jailed here because there are no special facilities for underage offenders.\xa0 Officials are building a separate facility for them on the grounds.', 'Women do have separate facilities at Juba Prison, but at the other prisons they are incarcerated with the men.', 'A dozen children live with their mothers in the prison.\xa0 When they reach two years of age they are supposed to leave and receive foster care outside.\xa0 Many are much older.\xa0 They stay on because there is no foster-care system.', 'Southern Sudan has no facilities for the mentally ill.\xa0 As a result, dangerous individuals are sent to the prisons.\xa0 The Public Health Ministry should be caring for them, but staff, funds and drugs are lacking.', 'Prison officials, with the United Nations and other donors, are trying to rehabilitate the facilities.', 'They are building a new kitchen and want to build a workshop so prisoners can learn a trade.', 'They also want to start a farm so the prisoners can learn to contribute to their communities after they are released.\xa0 But security concerns have prevented the launch of such projects.', 'A football game in the main courtyard provides exercise to some of the younger prisoners.\xa0 Others pass the time washing clothes or tending to small plots of potted vegetables.', 'Prisoners convicted of capital crimes are shackled with chains around their ankles.', 'Many sit on the ground playing board games or staring into space.', 'Wol says good facilities are essential for an effective prison system.\xa0 He also wants more trained corrections officers to upgrade his staff of mostly former soldiers.', '"You have to have the institutions.\xa0 Then should you provide the capacity, the rest will come automatically," he said. "Once you have the strong officers, once you have the strong laws, once you have the strong base, then you will overcome the rest of the thing [obstacles]."', 'The southern Sudanese government is building an academy outside Juba to train law enforcement officers.\xa0 But Wol notes that in a society with a literacy rate of less than 20 percent, every sector is competing for personnel with even basic skills.', 'Wol and his officers hope independence will attract more investment and expertise.\xa0 They will be needed if they are to build the institutions of the emerging nation and satisfy the aspirations of its long-suffering people.']