# Library Inclusion and Utilities

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from NLP import *
from itables import show
import itables.options as opt

/home/iskender/anaconda3/envs/bertopic-env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
guardian = pd.read_csv('../GuardianAPI/guardian_data_2010_2025_v2.csv')

# Tags

## Check Unique Tags

In [36]:
tags = combined['tags'].unique()

all_tags = []
for tag_str in tags:
    split_per_article = str(tag_str).split(',')
    for article_tags in split_per_article:
        split_by_semicolon = article_tags.split(';')
        all_tags.extend(split_by_semicolon)

unique_results = sorted(list(set(all_tags)))
print(unique_results)

[' #MeToo movement', " 'Global gag rule'", ' 21st Century Fox', ' 3', ' A&E', ' A-League Women', ' A-levels', ' AFL', ' AGL', ' ANC (African National Congress)', ' AOL', ' Abba', ' Abbey theatre', ' Abdel Fatah al-Sisi', ' Aberdeen', ' Abortion', ' Academics', ' Academies', ' Access to energy', ' Access to green space', ' Access to water', ' Accessories', ' Accountancy', ' Acne', ' Acting', ' Action and adventure films', ' Action games', ' Activate', ' Activism', ' Acupuncture', ' Adam Bandt', ' Adani Group', ' Adelaide', ' Adelaide United', ' Adelaide festival', ' Admissions', ' Adoption', ' Adrian Mole', ' Adrian Ramsay', ' Advance Australia', ' Advertising', ' Advertising Standards Authority', ' Advice for students', ' Afghanistan', ' Afghanistan cricket team', ' Africa', ' African Union', ' Agatha Christie', ' Aged care', ' Ageing', ' Agriculture', ' Aid', ' Aids and HIV', ' Air pollution', ' Air transport', ' Airbus', ' Airline industry', ' Al Aynsley-Green', ' Al Pacino', ' Al-Qaida', ' Alabama', ' Alan Bennett', ' Alan Joyce', ' Alan Partridge', ' Alanis Morissette', ' Albania', ' Alcohol', ' Alcoholism', ' Alec (American Legislative Exchange Council)', ' Alec Guinness', ' Aleppo', ' Alex Salmond', ' Alexander Lukashenko', ' Alexander McQueen', ' Alexander Zverev', ' Alexandria Ocasio-Cortez', ' Alexei Navalny', ' Alfred Hitchcock', ' Alfred Molina', ' Algeria', ' Alibaba', ' Alice Lowe', ' Alien life', ' All sectors', ' Allergies', ' Allotments', ' Almeida theatre', ' Alphabet', ' Alternative für Deutschland (AfD)', " Alzheimer's", ' Amadou and Mariam', ' Amanda Spielman', ' Amazon', ' Amazon Prime Video', ' Amazon rainforest', ' Amber Rudd', ' American Idol', ' American food and drink', ' Americana', ' Americas', ' Amnesty International', ' Anas Sarwar', ' Andre Agassi', ' Andrew Bailey', ' Andrew Bolt', ' Andrew Cuomo', ' Andrew Giles', ' Andrew Lansley', ' Andrew Lawrence', ' Andrew Tate', ' Android', ' Andrzej Wajda', ' André Villas-Boas', ' Andy Burnham', ' Andy Coulson', ' Andy Haldane', ' Andy Murray', ' Ang Lee', ' Angela Merkel', ' Angela Rayner', ' Angelina Jolie', ' Anglicanism', ' Angola', ' Angus Taylor', ' Animal behaviour', ' Animal welfare', ' Animals', ' Animation in film', ' Animation on TV', ' Anime', ' Annie Ernaux', ' Annie Nightingale', ' Another Year', ' Anthony Albanese', ' Anthony Fauci', ' Anthony Hopkins', ' Anthony Joshua', ' Anthropology', ' Anti-war movement', ' Antibiotics', ' Antisemitism', ' Anton Chekhov', ' Antonio Conte', ' Antony Blinken', ' Antony and the Johnsons', ' Anupama Chandrasekhar', ' Anxiety', ' Apple', ' Apple TV+', ' Apple WWDC', ' Apple Watch', ' Applying to university', ' Apprenticeships', ' Apps', ' Ara Darzi', ' Arab and Middle East unrest', ' Archaeology', ' Architecture', ' Arcola theatre', ' Argentina', ' Ariana Grande', ' Arianna Huffington', ' Arizona', ' Arkansas', ' Arlene Foster', ' Armenia', ' Arms trade', ' Arne Slot', ' Arnold Schwarzenegger', ' Arrested Development', ' Arsenal', ' Arsenal Women', ' Arsène Wenger', ' Art', ' Art and design', ' Artangel', ' Arthur Conan Doyle', ' Arthur Miller', ' Article 50', ' Artificial intelligence (AI)', ' Arts', ' Arts Council England', ' Arts education', ' Arts funding', ' Arts policy', ' Arundhati Roy', ' Aryna Sabalenka', ' As You Like It', ' Ashes 2021-22', ' Ashley Walters', ' Ashton Kutcher', ' Asia', ' Asia Pacific', ' Assisted dying', ' Asthma', ' AstraZeneca', ' Astronomy', ' Athletics', ' Atlanta', ' Atlanta United', ' Attention deficit hyperactivity disorder', ' Auckland', ' Audiences', ' Augusto Pinochet', ' Aukus', ' Aung San Suu Kyi', ' Austerity', ' Australia Day', ' Australia Olympic team', ' Australia Post', ' Australia cricket team', ' Australia holidays', ' Australia news', ' Australia rugby union team', ' Australia sport', ' Australia weather', ' Australian Broadcasting Corporation', ' Australian Competition and Consumer Commission (ACCC)', ' Australian Greens', ' Australian Open', ' Australian Open 2016', ' Australian books', ' Australian budget 2014', ' Australian budget 2024', ' Australian budget 2025', ' Australian economy', ' Australian education', ' Australian election 2019', ' Australian election 2025', ' Australian federal police', ' Australian film', ' Australian food and drink', ' Australian foreign policy', ' Australian immigration and asylum', ' Australian lifestyle', ' Australian media', ' Australian military', ' Australian music', ' Australian police and policing', " Australian politicians' expenses", ' Australian politics', ' Australian rules football', ' Australian security and counter-terrorism', ' Australian television', ' Australian theatre', ' Australian trade unions', ' Australian universities', ' Austria', ' Autism', ' Autobiography and memoir', ' Automotive emissions', ' Automotive industry', ' Autumn budget 2024', ' Autumn statement 2015', ' Awards and prizes', ' Ayatollah Ali Khamenei', ' Ayman al-Zawahiri', ' Azerbaijan', ' BAE Systems', ' BBC', ' BBC Four', ' BBC One', ' BBC Trust', ' BBC Two', ' BBC World Service', ' BHS', ' BNP', ' BP', ' BT', ' Baby P', ' Back pain', ' Badgers', ' Baftas', ' Bahamas', ' Bali', ' Ballet', ' Baltimore Ravens', ' Bangladesh', ' Bank of America', ' Bank of England', ' Banking', ' Banking ', ' Banking reform', ' Banks and building societies', ' Barack Obama', ' Barbados', ' Barbara Windsor', ' Barbican', ' Barbie', ' Barcelona', ' Barclays', ' Barnaby Joyce', ' Barratt Developments', ' Barry Cryer', ' Baseball', ' Bashar al-Assad', " Basil D'Oliveira", ' Basketball', ' Bath', ' Baton Rouge police shootings', ' Bayern Munich', ' Beach Boys', ' Beach holidays', ' Bear Grylls', ' Beauty', ' Bedfordshire', ' Beef', ' Beer', ' Bees', ' Behaviour', ' Behaviour management', ' Belarus', ' Belgium', ' Belvoir St Theatre', ' Ben Kingsley', ' Ben Stiller', ' Ben Stokes', ' Benefits', ' Benjamin Netanyahu', ' Bereavement', ' Berlin film festival', ' Berlin film festival 2017', ' Bernie Sanders', ' Best practice', ' Best practice exchange', ' Best practice: Winning new business', ' Beyoncé', ' Bhutan', ' Bibby Stockholm', ' Biden administration', ' Big Bash League', ' Bill Bailey', ' Bill Clinton', ' Bill Nighy', ' Bill Shorten', ' Billy Bragg', ' Billy Connolly', ' Billy Crystal', ' Binance', ' Biochemistry and molecular biology', ' Biodiversity', ' Biogenesis scandal', ' Biography books', ' Biology', ' Biotechnology industry', ' Bipolar disorder', ' Bird flu', ' Birds', ' Birmingham', ' Black British culture', ' Black Lives Matter movement', ' Black Sabbath', ' Black US culture', ' Blackpool', ' Blake Morrison', ' Blindness and visual impairment', ' Bloc Party', ' Blogging', ' Blue Origin', ' Blues', ' Blur', ' Bob Dylan', ' Bob Hawke', ' Bob Mortimer', ' Bobi Wine', ' Body image', ' Boeing', ' Boko Haram', ' Bolivia', ' Bollywood', ' Bon Jovi', ' Bondi Junction stabbings', ' Bonds', ' Bono', ' Booker prize', ' Booker prize 2011', ' Books', ' Booksellers', ' Boots', ' Boris Johnson', ' Borrowing & debt', ' Boundary changes', ' Bournemouth', ' Bowel cancer', ' Boxing', ' Boyhood', ' Bradford', ' Bradley Cooper', ' Brand', ' Brazil', ' Bread', ' Breast cancer', ' Breastfeeding', ' Breeders', ' Brentford', ' Brexit', ' Brian Cox', ' Brian Thompson shooting', ' Brics', " Bridget Jones' Diary", ' Bridget Phillipson', ' Brie Larson', ' Brighton & Hove Albion', ' Brighton festival', ' Brisbane', ' Bristol', ' British & Irish Lions', ' British American Tobacco', ' British Grand Prix', ' British Horseracing Authority', ' British army', ' British empire', ' British food and drink', ' British identity and society', ' Broadway', ' Brokeback Mountain', ' Brothers of Italy', ' Bruce Springsteen', ' Bruce Willis', ' Bryn Terfel', ' Bryson DeChambeau', ' Bubonic plague', ' Buckinghamshire', ' Buddhism', ' Budget', ' Budget 2016', ' Budget 2024 (spring)', ' Budget deficit', ' Building and town and country planning', ' Built Environment', ' Bukayo Saka', ' Bullying', ' Bundesliga', ' Burundi', ' Bushfires', ' Business', ' Business case', ' Business masterclasses', ' Business to business', ' Buying to let', ' Buzzcocks', ' CES', ' CIA', ' COP 21: Paris climate change conference 2015', ' Cabaret', ' Caitlin Clark', ' Caitlin Moran', ' California', ' California holidays', ' California wildfires', ' Calvin Harris', ' Cambridge', ' Cambridgeshire', ' Cameroon', ' Camping holidays', ' Canada', " Canada women's football team", ' Canary Islands holidays', ' Canberra', ' Cancer', ' Cancer research', ' Cannabis', ' Cannes 2011', ' Cannes 2012', ' Cannes 2013', ' Cannes 2014', ' Cannes 2015', ' Cannes 2019', ' Cannes 2023', ' Cannes film festival', ' Capita', ' Capital gains tax', ' Capital punishment', ' Captain America: Civil War', ' Captain Marvel', ' Car insurance', ' Cardiff', ' Care Quality Commission (CQC)', ' Care workers', ' Career choices', ' Careers', ' Careers advice', ' Careers in higher education', ' Carers', ' Carey Mulligan', ' Caribbean', ' Carillion', ' Carl Barât', ' Carlo Ancelotti', ' Carlos Acosta', ' Caroline Criado Perez', ' Carrie Fisher', ' Cary Grant', ' Case studies', ' Catalonia', ' Cate Blanchett', ' Catherine', ' Catherine Deneuve', ' Catholicism', ' Cats', ' Cattle', ' Caution', ' Celebrity', ' Celia Imrie', ' Censorship', ' Census', ' Census 2016', ' Central government', ' Centrelink', ' Centrelink debt recovery', ' Cereals and grains', ' Cervical cancer', ' Cetaceans', ' Chad', ' Chagos Islands', ' Champions League', ' Champions League 2009-10', ' Champions League 2011-12', ' Championship', ' Championship 2012-13', ' Chanel', ' Channel 4', ' Channing Tatum', ' Chappell Roan', ' Charities', ' Charity Awards', ' Charles Manson', ' Charlie Chaplin', ' Charlie Hebdo', ' Charlie Hebdo attack', ' Charlie Kaufman', ' Charlie Parker', ' Charlie Watts', ' Charlotte Rampling', ' Charlton Heston', ' ChatGPT', ' Chatbots', ' Chechnya', ' Cheese', ' Chefs', ' Chelsea', ' Chelsea flower show', ' Cheltenham', ' Chemical industry', ' Chemistry', ' Chess', ' Chester', ' Chicago', ' Child benefits', ' Child labour', ' Child marriage', ' Child protection', ' Child rights', ' Childbirth', ' Childcare', ' Childcare Australia', ' Children', ' Children and teenagers', " Children's TV", " Children's health", " Children's rights", " Children's tech", " Children's theatre", ' Chile', ' Chimamanda Ngozi Adichie', ' China', " China's one-child policy", ' Chinese Super League', ' Chloë Grace Moretz', ' Chloë Sevigny', ' Chocolate', ' Cholera', ' Chris Bowen', ' Chris Gayle', ' Chris Hemsworth', ' Chris Huhne', ' Chris Minns', ' Chris Philp', ' Chris Skidmore', ' Chris Ware', ' Chris Whitty', ' Christian Bale', ' Christian Porter', ' Christianity', ' Christine Lagarde', ' Christmas', ' Christmas markets', ' Christmas shows', ' Christopher Luxon', ' Christopher Pyne', ' Christopher Walken', ' Chuck Schumer', ' Cincinnati Bengals', ' Cindy Sherman', ' Cirque du Soleil', ' Cities', ' Cities and development', ' Citigroup', ' City apps', ' City breaks', ' Civil liberties - international', ' Civil service', ' Civil society', ' Clarence Thomas', ' Class issues', ' Classical music', ' Classics', ' Classics and ancient history', ' Clermont Auvergne', ' Climate Change Committee', ' Climate aid', ' Climate change', ' Climate crisis', ' Climate finance', ' Climate science', ' Climate science scepticism and denial', ' Clive Lewis', ' Clive Owen', ' Club World Cup', ' Club culture', ' Coal', ' Coalition', ' Coastlines', ' Coca-Cola', ' Cocktails', ' Coffee', ' Cold war', ' Coleen Rooney', ' Coles', ' Colin Firth', ' College basketball', ' College football', ' College sports', ' Colleges', ' Colombia', ' Colonialism', ' Colorado', ' Colorado attack', ' Colorado wildfires 2012', ' Comcast', ' Comedy', ' Comedy films', ' Comets', ' Comics and graphic novels', ' Commercial property', ' Commissioning', ' Commodities', ' Commons speaker', ' Commonwealth Games', ' Commonwealth and Development Office', ' Commonwealth of Nations', ' Commonwealth summit', ' Communication', ' Communications', ' Communism', ' Communities', ' Community building', ' Commuting', ' Competition and Markets Authority', ' Computing', ' Conclave', ' Concussion in sport', ' Condé Nast', ' Conferences', ' Conflict and arms', ' Connacht', ' Consciousness', ' Conservation', ' Conservation and indigenous people', ' Conservative conference', ' Conservative conference 2023', ' Conservative leadership', ' Conservatives', ' Constitutional reform', ' Construction industry', ' Consumer affairs', ' Consumer magazines', ' Consumer rights', ' Consumer spending', ' Contraception and family planning', ' Cop15', ' Cop26', ' Cop27', ' Cop28', ' Coral', ' Cornel West', ' Cornwall', ' Cornwall holidays', ' Coronavirus', ' Corporate governance', ' Corporate social responsibility', ' Corporate sponsorship', ' Corruption index and barometer', ' Cory Booker', ' Cosmetic surgery', ' Cost of living crisis', ' Cost-of-living crisis', ' Council tax', ' Counselling and therapy', ' Counter-terrorism policy', ' Country', ' County Championship', ' County Durham', ' Couriers/delivery industry', ' Court of appeal', ' Court of justice of the European Union', ' Courteeners', ' Covid inquiry', ' Craft', ' Craft and hobbies books', ' Craig Kelly', ' Crawley Town', ' Creative writing', ' Credit cards', ' Cricket', ' Cricket World Cup 2023', ' Crime', ' Crime - Australia', ' Crime films', ' Crimea', ' Criminal justice', ' Cristiano Ronaldo', ' Croatia', ' Crosswords', ' Crouching Tiger', ' Crowdfunding', ' Crowdsourcing', ' Crown Prosecution Service', ' Cryptocurrencies', ' Crystal Palace', ' Cuba', ' Cultural Olympiad', ' Cultural trips', ' Culture', ' Currencies', ' Curriculums', ' Curry', ' Cuts and closures', ' Cybercrime', ' Cycling', ' Cycling holidays', ' Cynthia Erivo', ' Cyprus', ' Cyril Ramaphosa', ' Czech Republic', ' DC Comics', ' DEI policies', ' DIY', ' DNA database', ' DS Smith', ' Daily Mail', ' Daily Telegraph', ' Dakota Johnson', ' Dalits', ' Dallas', ' Damian Lewis', ' Dance', ' Dance music', ' Dangerous dogs', ' Daniel Andrews', ' Daniel Barenboim', ' Daniel Craig', ' Daniel Ek', ' Danny Huston', ' Dapper Laughs', ' Darcey Bussell', ' Darfur', ' Darren Jones', ' Dartmoor', ' Darwin', ' Data', ' Data and computer security', ' Data management', ' Data protection', ' Dating', ' David Bowie', ' David Byrne', ' David Cameron', ' David Carradine', ' David Crisafulli', ' David Cronenberg', ' David Davis', ' David Dimbleby', ' David Duchovny', ' David Gordon Green', ' David Hare', ' David Hicks', ' David Hockney', ' David Lammy', ' David Littleproud', ' David Lodge', ' David Lynch', ' David Pocock', ' David Shrigley', ' Davos', ' Davos 2010', ' Davos 2012', ' Davos 2014', ' Dawn French', ' Dawn of the Planet of the Apes', ' Deafness and hearing loss', ' Death and dying', ' Deaths in custody', ' Debbie Reynolds', ' Debit cards', ' Debt relief', ' Deepfake', ' Deepwater Horizon oil spill', ' Defamation law', ' Defamation law (Australia)', ' Defence policy', ' Deflategate', ' Deforestation', ' Dele Alli', ' Delhi', ' Deliveroo', ' Dell', ' Dementia', ' Demi Moore', ' Democratic Republic of the Congo', ' Democratic Unionist party (DUP)', ' Democrats', ' Demos', ' Dengue fever', ' Denmark', ' Dentistry', ' Dentists', ' Denver', ' Denver Broncos', ' Department for Education', ' Depopulation', ' Depression', ' Derby County', ' Derbyshire holidays', ' Derek Jacobi', ' Derry', ' Desertification', ' Design', ' Desmond Tutu', ' Deutsche Bank', ' Development', ' Development finance', ' Devolution', ' Devon', ' Devon holidays', ' Diabetes', ' Diamonds', ' Diana Athill', ' Diane Abbott', ' Diane Keaton', ' Dick King-Smith', ' Dick Van Dyke', ' Didier Drogba', ' Diego Costa', ' Diego Rivera', ' Diets and dieting', ' Digestive disorders', ' Digital Britain', ' Digital media', ' Dior', ' Disability', ' Disco', ' Discrimination at work', ' Disney Channel', ' Disney+', ' Diversity', ' Diving', ' Diving holidays', ' Divorce', ' Doctor Strange', ' Doctor Who', ' Doctors', ' Documentary', ' Documentary films', ' Dogs', ' Dolly Parton', ' Domestic violence', ' Domestic workers', ' Dominican Republic', " Domino's Pizza", " Don't Look Now", ' Donald Trump', ' Donald Trump Jr', ' Donald Trump inauguration', ' Donald Trump trials', ' Doncaster', ' Donmar Warehouse', ' Donna Tartt', ' Dorset holidays', ' Doves', ' Draft Day', ' Drag', " Dragons' Den", ' Drama', ' Drama and dance', ' Drama films', ' Drawing', ' Dresses', ' Drought', ' Drug resistance', ' Drugs', ' Drugs in sport', ' Drugs policy', ' Drugs trade', ' DuPont', ' Dua Lipa', ' Dubai', ' Dublin', ' Dundee Rep', ' Durham University', ' Dustin Hoffman', ' Dynamo Kyiv', ' E coli', ' E-commerce', ' ECB', ' EDF Energy', ' EY', ' Early years education', ' Earthquakes', ' East Sussex', ' Eastern European food and drink', ' Eating disorders', ' Ebola', ' Ebrahim Raisi', ' Economic growth (GDP)', ' Economic policy', ' Economic recovery', ' Economics', ' Ecuador', ' Eczema', ' Ed Balls', ' Ed Davey', ' Ed Miliband', ' Ed Sheeran', ' Ed Vaizey', ' Eddie Redmayne', ' Edgar Degas', ' Edinburgh', ' Edinburgh festival', ' Edinburgh festival 2018', ' Edinburgh festival 2019', ' Edinburgh festival 2023', ' Education', ' Education policy', ' Efficiency', ' Efficiency and risk', ' Eggs', ' Egypt', ' Eimear McBride', ' El Greco', ' El Niño southern oscillation', ' El Salvador', ' Elections past', ' Electoral reform', ' Electric', ' Electric vehicles', ' Electronic music', ' Elizabeth Gilbert', ' Elon Musk', ' Email', ' Emergency services', ' Emerging markets', ' Emily Maitlis', ' Emily Thornberry', ' Eminem', ' Emma Hayes', ' Emmanuel Macron', ' Emmeline Pankhurst', ' Employability', ' Employee benefits', ' Employment', ' Employment law', ' Employment tribunals', ' Endangered habitats', ' Endangered species', ' Endometriosis', ' Energy', ' Energy bills', ' Energy efficiency', ' Energy industry', ' Energy research', ' Engagement', ' Engaging employees', ' Engineering', ' England', ' England cricket team', ' England holidays', ' England riots 2011', ' England rugby union team', ' England v New Zealand 2021', " England women's cricket team", " England women's football team", ' English and creative writing', ' Entrepreneurs', ' Environment', ' Environment Agency', ' Environmental activism', ' Environmental sustainability', ' Epidemics', ' Epilepsy', ' Equal marriage', ' Equality Act 2010', ' Equality and Human Rights Commission (EHRC)', ' Equatorial Guinea', ' Equity release', ' Eric Adams', ' Erin Patterson mushroom trial', ' Ernest Hemingway', ' Errollyn Wallen', ' Espionage', ' Essays', ' Essex', ' Estonia', ' Eswatini', ' Eta', ' Ethan Hawke', ' Ethical and green living', ' Ethical business', ' Ethics', ' Ethiopia', ' Euro', ' Euro 2020', ' Euro 2024', ' Europa League', ' Europe', ' Europe holidays', ' Europe weather', ' European Central Bank', ' European Championship', ' European Commission', ' European Tour', ' European Union', ' European banks', ' European club football', ' European elections', ' European monetary union', ' Eurovision', ' Eurozone crisis', ' Evangelical Christianity', ' Everton', ' Evolution', ' Ewan McGregor', ' Exams', ' Executive pay and bonuses', ' Exeter', ' Exhibitions', ' Experimental music', ' Extinction Rebellion', ' Extreme heat', ' Extreme weather', ' ExxonMobil', ' F Scott Fitzgerald', ' FA Cup', ' FA Cup 2010-11', ' FBI', ' FC Cincinnati', ' FC United of Manchester', ' FTSE', ' Facebook', ' Factual TV', ' Falkirk', ' Falkland Islands', ' Family', ' Family finances', ' Family holidays', ' Famine', ' Fantasy TV', ' Fantasy books', ' Far right', ' Far right (US)', ' Farm animals', ' Farming', ' Fashion', ' Fashion industry', ' Fashion weeks', ' Fast food', ' Fatima Payman', ' Female genital mutilation (FGM)', ' Feminism', ' Fencing', ' Fenerbahce', ' Fentanyl', ' Fernando Alonso', ' Fernando Torres', ' Ferrari', ' Ferry travel', ' Fertility problems', ' Festivals', ' Fibromyalgia', ' Fiction', ' 

## Clean Tags

In [18]:
tag_clean_df = clean_tags(guardian,["living longer","ageing well", "well ageing", "aging well", "well aging"])

Kept 584 of 58444 articles related to ageing.

In [20]:
tag_clean_df.groupby('topic_key')['id'].count()

topic_key
Health_wellbeing    127
ageing              364
aging                43
anti-ageing           1
longevity            49
Name: id, dtype: int64

In [5]:
show(tag_clean_df[['section','headline','trailText', 'tags']], scrollY="500px", scrollCollapse=True)

In [13]:
topic_model, topic_info, guardian_out = analyze_bertopic(tag_clean_df, v_min_df=1, v_max_df=0.6,text_col="bodyText",top_n_words=30,
                                     save_csv=None)

2025-08-14 16:32:04,987 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████████████████████████████| 19/19 [02:34<00:00,  8.15s/it]
2025-08-14 16:34:39,989 - BERTopic - Embedding - Completed ✓
2025-08-14 16:34:39,990 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-08-14 16:34:40,335 - BERTopic - Dimensionality - Completed ✓
2025-08-14 16:34:40,335 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-08-14 16:34:40,352 - BERTopic - Cluster - Completed ✓
2025-08-14 16:34:40,353 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-08-14 16:34:41,040 - BERTopic - Representation - Completed ✓
2025-08-14 16:34:41,041 - BERTopic - Topic reduction - Reducing number of topics
2025-08-14 16:34:41,044 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-08-14 16:34:41,757 - BERTopic - Representation - Completed ✓
2025-08-14 16:34:41,758 - BERTopic - Topic reduction - Reduced number of topics from 12 to 12

In [14]:
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,149,-1_menopause_lonely_immune_frank,"[menopause, lonely, immune, frank, sue, streng...","[Forget lifespan: increasingly, healthspan – t..."
1,0,116,0_cells_mice_telomeres_senescent,"[cells, mice, telomeres, senescent, cell, sene...","[In the summer of 2019, months before the word..."
2,1,57,1_aged care_residents_patient_dad,"[aged care, residents, patient, dad, mum, care...","[The hyperbole used by politicians, bureaucrat..."
3,2,56,2_pensions_workers_healthy life_state pension,"[pensions, workers, healthy life, state pensio...","[For much of human history, life was well desc..."
4,3,46,3_collagen_anti ageing_cosmetic_wrinkles,"[collagen, anti ageing, cosmetic, wrinkles, bo...",[One cold and wet day in what passes for sprin...
5,4,42,4_curcumin_marmalade_centenarians_japanese,"[curcumin, marmalade, centenarians, japanese, ...",[While Kamal Patel was probing through the rea...
6,5,33,5_theatre_actors_aaron_rossellini,"[theatre, actors, aaron, rossellini, anger, ze...",[Brooke Adams was a huge star in her 30s after...
7,6,29,6_midlife_gracefully_ageing gracefully_neiman,"[midlife, gracefully, ageing gracefully, neima...",[There’s a great scene in Fried Green Tomatoes...
8,7,17,7_synaesthesia_synaesthetes_hearing loss_reed,"[synaesthesia, synaesthetes, hearing loss, ree...",[Urgent action needs to be taken across societ...
9,8,14,8_paxman_age discrimination_mature_pensioners,"[paxman, age discrimination, mature, pensioner...",[The UK is “completely and institutionally age...
10,9,14,9_sleeping_brain health_physical activity_bili...,"[sleeping, brain health, physical activity, bi...",[Two nights of broken sleep are enough to make...
11,10,11,10_life care_palliative_palliative care_syme,"[life care, palliative, palliative care, syme,...","[End-of-life care, catapulted into the public ..."

In [15]:
full_keyword_getter(guardian_out)

-1.0 → ['menopause', 'lonely', 'immune', 'frank', 'sue', 'strength', 'dancing', 'eddie', 'screening', 'cells', 'residents', 'mum', 'tech', 'characters', 'sussman', 'pavey', 'workers', 'leg', 'played', 'age group', 'sexually', 'honoré', 'partners', 'standing', 'design', 'centenarians', 'radio', 'age uk', 'older women', 'wall']
0.0 → ['cells', 'mice', 'telomeres', 'senescent', 'cell', 'senescent cells', 'ageing process', 'stem', 'dna', 'biological age', 'plasma', 'gene', 'young blood', 'treatments', 'anti ageing', 'immune', 'coray', 'wyss coray', 'wyss', 'stem cells', 'tissues', 'mouse', 'proteins', 'experiments', 'tropical', 'related diseases', 'tissue', 'villeda', 'protein', 'meditation']
1.0 → ['aged care', 'residents', 'patient', 'dad', 'mum', 'carers', 'abuse', 'residential', 'workers', 'village', 'councils', 'care services', 'emergency', 'houses', 'carer', 'clients', 'design', 'unpaid', 'visits', 'health social', 'providers', 'remote', 'staffing', 'elder abuse', 'accommodation', 'brother', 'hogeweyk', 'fund', 'admissions', 'people dementia']
2.0 → ['pensions', 'workers', 'healthy life', 'state pension', 'employers', 'harper', 'workforce', 'poor health', 'inequalities', 'treasury', 'employees', 'fertility', 'retirement age', 'new hampshire', 'pension age', 'hampshire', 'gdp', 'ons', 'public sector', 'pensioners', 'transition', 'working age', 'older workers', 'lowest', 'intergenerational', 'scott', 'life expectancies', 'productivity', 'expectancies', 'longer life']
3.0 → ['collagen', 'anti ageing', 'cosmetic', 'wrinkles', 'botox', 'serum', 'cream', 'nirdosh', 'skincare', 'dr nirdosh', 'creams', 'supplements', 'lines', 'claims', 'procedures', 'ingredients', 'fashion', 'cosmetic surgery', '30ml', 'dermatologists', 'pollution', 'sun', 'peptides', 'product', 'boots', 'facial', 'guiliano', 'skin ageing', 'steroids', 'vitamin']
4.0 → ['curcumin', 'marmalade', 'centenarians', 'japanese', 'vegetables', 'island', 'fruit', 'mediterranean', 'ikaria', 'yoghurt', 'toxic', 'world oldest', 'mediterranean diet', 'spain', 'branyas', 'meat', 'longest', 'tokyo', 'diets', 'buettner', 'rice', 'turmeric', 'kimura', 'february', 'records', 'dietary', 'ikarians', 'green tea', '110', 'okinawa']
5.0 → ['theatre', 'actors', 'aaron', 'rossellini', 'anger', 'zeldin', 'older women', 'novel', 'invisibility', 'festival', 'invisible', 'adams', 'midlife', 'drama', 'angry', 'comedy', 'films', 'novels', 'payne', 'gregorio', 'di gregorio', 'midlife crisis', 'di', 'eastwood', 'bridge', 'menopause', 'character', 'segal', 'rage', 'mrs']
6.0 → ['midlife', 'gracefully', 'ageing gracefully', 'neiman', 'wolpert', 'phrase', 'tomorrow', 'sarcasm', 'bob', 'great great', 'maturity', 'dislike', 'malaise', 'songs', 'pleasures', 'song', 'pretend', 'old man', 'student', 'utterly', 'mountain', 'edinburgh', 'apparently', 'dad', 'harrison', 'miserable', 'moore', 'boys', 'hell', 'genius']
7.0 → ['synaesthesia', 'synaesthetes', 'hearing loss', 'reed', 'dementia research', 'cure', 'dementia risk', 'non synaesthetes', 'says reed', 'donanemab', 'colours', 'amyloid', 'treatments', 'hearing aids', 'alzheimer research', 'functions', 'risk factors', 'effectiveness', 'people dementia', 'evans', 'aids', 'risk dementia', 'onset', 'lawrence', 'cholesterol', 'dementia patients', 'neurological', 'early stages', 'occupational', 'patient']
8.0 → ['paxman', 'age discrimination', 'mature', 'pensioners', 'tory', 'vote', 'ageist', 'pensioner', 'simpson', 'racism', 'time work', 'human rights', 'equality', 'brexit', 'employers', 'age uk', 'ehrc', 'courts', 'prevalent', 'remarks', 'characteristics', 'ireland', 'chief executive', 'acceptable', 'perceptions', 'abilities', 'presumably', 'inquiry', 'celebrity', 'politics']
9.0 → ['sleeping', 'brain health', 'physical activity', 'bilingual', 'hartshorne', 'asleep', 'grey matter', 'volume', 'nights', 'cortex', 'noise', 'cognitively', 'hours night', 'functioning', 'hours sleep', 'brain ageing', 'helpful', 'foster', 'brain function', 'teens', 'reserve', 'slept', 'languages', 'insomnia', 'night sleep', 'decision making', 'vocabulary', 'cats', 'older adults', 'ownership']
10.0 → ['life care', 'palliative', 'palliative care', 'syme', 'hartley', 'cemetery', 'burial', 'cremation', 'funeral', 'aid dying', 'middleton green', 'cemeteries', 'middleton', 'mccartney', 'buried', 'assisted', 'jenny', 'catholic', 'saumarez', 'assisted dying', 'hospice', 'euthanasia', 'graves', 'patient', 'erica', 'oregon', 'site', 'grave', 'suicide', 'church']

In [10]:
guardian_out

,id,section,pub_date,web_url,headline,trailText,byline,wordcount,bodyText,links,authors,tags,topic_key,topic,topic_prob,topic_keywords
0,society/joepublic/2010/dec/30/nhs-older-people,Society,2010-12-30T10:05:00Z,https://www.theguardian.com/society/joepublic/...,We need an NHS for later life,<p>A health and care structure which treats ol...,Michelle Mitchell,788,The dramatic increase in life expectancy over ...,http://www.ageuk.org.uk/,Michelle Mitchell,Older people; Society; Long-term care; Health;...,Health_wellbeing,0.0,0.544301,"[mice, anti ageing, pension, residents, house,..."
1,science/2010/sep/05/anti-ageing-america-arlene...,Science,2010-09-04T23:07:07Z,https://www.theguardian.com/science/2010/sep/0...,America's $88bn anti-ageing industry: dangerou...,<p>A new book warns that millions face serious...,by Paul Harris in New York,743,The desire to defy age is as ancient as human ...,NaN,Paul Harris,Ageing; US healthcare; US news; World news; Sc...,Health_wellbeing,0.0,0.722994,"[mice, anti ageing, pension, residents, house,..."
2,world/2010/aug/01/japan-women-life-expectancy-...,World news,2010-08-01T14:09:39Z,https://www.theguardian.com/world/2010/aug/01/...,Japan's women toast their own health as life e...,"<p>Now living to an average of 86.4, Japanese ...",Justin McCurry in Tokyo,591,Eriko Maeda could be forgiven for succumbing t...,http://www.theguardian.com/world/video/2010/ja...,Justin McCurry,Japan; Ageing; Health; World news; Health & we...,Health_wellbeing,0.0,1.000000,"[mice, anti ageing, pension, residents, house,..."
3,lifeandstyle/2011/oct/21/taste-changes-with-ag...,Life and style,2011-10-21T21:59:19Z,https://www.theguardian.com/lifeandstyle/2011/...,"Food for Fort: how taste changes with age, plu...",<p>My mother's sense of taste has declined wit...,Matthew Fort,257,My mother's sense of taste has deteriorated wi...,http://www.ageuk.org.uk/health-wellbeing/healt...,Matthew Fort,Food; Ageing; Life and style,Health_wellbeing,0.0,0.774659,"[mice, anti ageing, pension, residents, house,..."
4,society/2011/sep/18/no-age-limit-fight-health,Society,2011-09-18T20:00:03Z,https://www.theguardian.com/society/2011/sep/1...,There is no age limit in the fight for health,<strong>Letters: </strong>The impact of non-c...,NaN,304,This week the United Nations is bringing toget...,http://www.theguardian.com/society/2011/sep/16...,NaN,Older people; World Health Organization; Healt...,Health_wellbeing,1.0,1.000000,"[synaesthesia, synaesthetes, reed, says reed, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579,us-news/2024/feb/06/edie-ceccarelli-us-oldest-...,US news,2024-02-06T12:00:32Z,https://www.theguardian.com/us-news/2024/feb/0...,Sweet 116: town throws birthday bash for Ameri...,"Parade honors Edie Ceccarelli, who says the se...","Maanvi Singh in Willits, California",871,"In the small, northern California town of Will...",https://www.willitsnews.com/2012/03/07/letter-...,Maanvi Singh,California; US news; Ageing; Life and style; W...,longevity,-1.0,0.214423,"[immune, lonely, sexually, friendships, techno..."
580,wellness/2024/apr/28/advice-100-year-old-peopl...,Wellness,2024-04-28T11:00:05Z,https://www.theguardian.com/wellness/2024/apr/...,A ‘longevity revolution’ is coming. Here’s how...,"Life at its essence is about time and by 2050,...",William J Kole,1185,"Loneliness. Ageism. Physical limitations, cogn...",https://time.com/6320381/americans-super-aging...,NaN,Well actually; Ageing; Life and style,longevity,0.0,0.619676,"[mice, anti ageing, pension, residents, house,..."
581,lifeandstyle/2024/feb/05/touch-your-toes-six-f...,Life and style,2024-02-05T10:00:11Z,https://www.theguardian.com/lifeandstyle/2024/...,"Touch your toes! Six fast, easy ways to improv...",Poor mobility can have a huge impact on your l...,Zoe Williams,1684,Remember the mobility challenge that went vira...,https://www.tiktok.com/@emiwong_/video/7247505...,Zoe Williams,Health & wellbeing; Fitness; Life and style; A...,longevity,0.0,0.286410,"[mice, anti ageing, pension, residents, house,..."
582,lifeandstyle/2025/apr/07/a-tub-a-day-might-eat...,Life and style,2025-04-06T15:00:54Z,https://www.theguardian.com/lifeandstyle/2025/...,A tub a day: might eating yoghurt help you liv...,When the world’s oldest woman passed away at 1...,Bianca Nogrady,880,Supercentenarians – humans who live beyond 110...,https://www.theguardian.com/world/2025/mar/13/...,Bianca Nogrady,Health & wellbeing; Ageing; Science; Life and ...,longevity,0.0,1.000000,"[mice, anti ageing, pension, residents, house,..."
583,science/2019/feb/19/infusions-young-blood-not-...,Science,2019-02-19T21:47:46Z,https://www.theguardian.com/science/2019/feb/1...,Infusions of young blood not proven 'safe or e...,FDA warning is blow to anti-age treatment fad ...,Adam Gabbatt in New York,368,The US government has warned that older people...,https://www.fda.gov/NewsEvents/Newsroom/PressA...,Adam Gabbatt,Ageing; Science; US news,anti-ageing,0.0,0.625144,"[mice, anti ageing, pension, residents, house,..."

In [21]:
guardian_out.to_csv('../GuardianAPI/guardian_cleared1_v2.csv',index=False)

In [30]:
guardian_exp = pd.read_csv('../GuardianAPI/guardian_data_2023_2025_experiment.csv')

In [31]:
show(guardian_exp[['section','headline','trailText', 'tags']], scrollY="500px", scrollCollapse=True)

In [41]:
guardian_exp2 = pd.read_csv('../GuardianAPI/guardian_data_2023_2025_experiment2.csv')

In [7]:
def clean_sections(df: pd.DataFrame, sections_to_keep:list[str]) -> pd.DataFrame:
    base_keep_sections = [
        #main ones
        'Business',
        'Opinion',
        'Science',
        'Life and style',
        'Society',
        'Fashion',
        #supplementary ones
        # 'Australia News',
        # 'US news',
        # 'UK news',
        'World News'
        'Technology',
        'Food',
        'Environment',
        'Wellness',
        'Healthcare Professionals Network',
        'Education',
        'News',
        'Sport',
        'Inequality',
        'Fashion',
        'Help',
        'Health revolution',
        'wellbeing at work',
        'Australian Unity: Real Wellbeing',
        'Australian Digital Health Agency: Well connected'
        'Industry Super Australia: Retiring well'
    ]

    base_keep_sections.extend(sections_to_keep)

    filtered_df = df[df['section'].isin(base_keep_sections)]
    
    print(f"The dataset shrinked from {len(df)} to {len(filtered_df)}")
    
    return filtered_df

In [66]:
show(clean_sections(guardian_exp3,[])[['section','headline','trailText', 'tags']], scrollY="500px", scrollCollapse=True)

The dataset shrinked from 214 to 124

In [55]:
show(guardian_exp3[['section','headline','trailText', 'tags']], scrollY="500px", scrollCollapse=True)

In [52]:
guardian_exp3 = pd.read_csv('../GuardianAPI/guardian_data_2023_2025_experiment3.csv')

In [53]:
show(guardian_exp3[['section','headline','trailText', 'tags']], scrollY="500px", scrollCollapse=True)

In [67]:
guardian_exp4 = pd.read_csv('../GuardianAPI/guardian_data_2010_2025_experiment4.csv')

In [69]:
show(guardian_exp4[['section','headline','trailText', 'tags']], scrollY="500px", scrollCollapse=True)

In [73]:
section_clean_exp4 = clean_sections(guardian_exp4,[])

The dataset shrinked from 923 to 569

In [79]:
show(clean_tags(section_clean_exp4,[])[['section','headline','trailText', 'tags']], scrollY="500px", scrollCollapse=True)

Kept 121 of 569 articles related to ageing.

In [87]:
guardian_exp5 = pd.read_csv('../GuardianAPI/guardian_data_2010_2025_experiment5.csv')

In [88]:
show(guardian_exp5[['section','headline','trailText', 'tags']], scrollY="500px", scrollCollapse=True)

In [89]:
section_clean_exp5 = clean_sections(guardian_exp5,[])

The dataset shrinked from 943 to 272

In [90]:
show(section_clean_exp5[['section','headline','trailText', 'tags']], scrollY="500px", scrollCollapse=True)

In [91]:
tag_clean_exp5 = clean_tags(section_clean_exp5,[])

Kept 11 of 272 articles related to ageing.

In [92]:
show(tag_clean_exp5[['section','headline','trailText', 'tags']], scrollY="500px", scrollCollapse=True)

In [86]:
clean_sections(tag_clean_exp5,[])

The dataset shrinked from 17 to 11

,id,section,pub_date,web_url,headline,trailText,byline,wordcount,bodyText,links,authors,tags,topic_key
1,fashion/2017/may/22/clothes-designer-alexa-chu...,Fashion,2017-05-22T12:28:09Z,https://www.theguardian.com/fashion/2017/may/2...,Anyone who loves clothes can be a designer now...,"Like Samantha Cameron and Victoria Beckham, sh...",Hadley Freeman,960,Do you have any thoughts on Alexa Chung’s fash...,https://www.nytimes.com/2017/04/28/opinion/cli...,Hadley Freeman,Fashion; Life and style; Alexa Chung; Samantha...,donald trump
2,commentisfree/2017/jul/30/a-brief-guide-to-ete...,Opinion,2017-07-30T16:00:24Z,https://www.theguardian.com/commentisfree/2017...,"A brief guide to eternal youth – get a dog, av...",Recent studies suggest that being neurotic and...,Arwa Mahdawi,938,You know what never gets old? Nothing. We are ...,http://journals.sagepub.com/doi/full/10.1177/0...,Arwa Mahdawi,Health & wellbeing; Life and style; Ageing,donald trump
3,commentisfree/2018/jul/01/danielle-rowley-peri...,Opinion,2018-07-01T05:00:36Z,https://www.theguardian.com/commentisfree/2018...,Talking about periods is part of a welcome dec...,Brave female MPs are leading the way in the de...,Barbara Ellen,1024,It’s rarely felt so good to see a woman talk a...,https://www.theguardian.com/politics/video/201...,Barbara Ellen,Menstruation; Abortion; Women; World news; Sca...,donald trump
4,commentisfree/2018/dec/02/we-applaud-the-activ...,Opinion,2018-12-02T06:00:26Z,https://www.theguardian.com/commentisfree/2018...,We applaud the active old but if they carry on...,Eileen Jolly sued her company because she want...,Catherine Bennett,982,"For anyone the wrong side of 60, last week’s t...",https://www.theguardian.com/politics/2018/nov/...,Catherine Bennett,Older people; Society; Young people; Alzheimer...,donald trump
5,commentisfree/2018/oct/06/congress-senate-hous...,Opinion,2018-10-06T16:26:17Z,https://www.theguardian.com/commentisfree/2018...,America has become a gerontocracy. We must cha...,The average age of a congressional representat...,Daniel Bessner and David Austin Walsh,925,The United States has a gerontocracy problem. ...,https://www.theguardian.com/commentisfree/2018...,Daniel Bessner; David Austin Walsh,US politics; Ageing; Democrats; Republicans,donald trump
7,commentisfree/2019/mar/08/frozen-eggs-women-ba...,Opinion,2019-03-08T06:59:37Z,https://www.theguardian.com/commentisfree/2019...,"I’ve frozen my eggs, but women shouldn’t have ...",We are having fewer children and living longer...,Dearbhail McDonald,1202,It’s a long road from playing with baby dolls ...,https://www.theguardian.com/world/2018/dec/26/...,Dearbhail McDonald,Population; World news; Reproduction; Ageing; ...,donald trump
8,society/2020/dec/20/the-age-of-wisdom-why-our-...,Society,2020-12-20T08:45:13Z,https://www.theguardian.com/society/2020/dec/2...,The age of wisdom: why our elders were the bes...,"Biden, Jagger, Mirren… as celebrity septuagena...",Andrew Anthony,1434,Among the many effects of the pandemic is the ...,https://www.theguardian.com/australia-news/202...,Andrew Anthony,Older people; Ageing; Society; Culture; Corona...,donald trump
9,commentisfree/2021/nov/09/biden-and-his-senato...,Opinion,2021-11-09T15:12:08Z,https://www.theguardian.com/commentisfree/2021...,The president and Senate are the oldest in US ...,There’s nothing wrong with politicians being i...,Arwa Mahdawi,704,"Nikki Haley should have joined the circus, bec...",https://apnews.com/article/donald-trump-orange...,Arwa Mahdawi,US Congress; US politics; US news; World news;...,donald trump
10,society/2021/may/30/lionel-shriver-should-we-s...,Society,2021-05-30T06:00:47Z,https://www.theguardian.com/society/2021/may/3...,Lionel Shriver: ‘A chosen death is an authoria...,The author’s new novel centres around an elder...,Lionel Shriver,2937,"For those of us with elderly parents, countles...",https://guardianbookshop.com/should-we-stay-or...,Lionel Shriver,Assisted dying; Ageing; Death and dying; Ficti...,donald trump
15,commentisfree/article/2024/jul/07/biden-putin-...,Opinion,2024-07-07T07:00:02Z,https://www.theguardian.com/commentisfree/arti...,"Biden, Putin, Xi, Modi: what is it that keeps ...",We live in societies that celebrate youth and ...,Kenan Malik,1121,‘States when they are in difficulties or in fe...,https://penelope.uchicago.edu/Thayer/E/Roman/T...,Kenan Malik,Joe Biden; US elections 2024; US news; Donald ...,donald trump
16,business/2025/jun/01/when-are-people-too-old-t...,Business,2025-06-01T14:00:14Z,https://www.theguardian.com/business/2025/jun/...,When are people too old to do their jobs?,While half of people over 50 are being pushed ...,Gene Marks,777,Old people are making news. Just this past wee...,https://www.euronews.com/business/2025/05/26/e...,Gene Marks,US small business; Business; Ageing; US news,donald trump

In [5]:
guardian_topic0 = pd.read_csv('../GuardianAPI/guardian_data_2010_2025_topic0_v2.csv')

In [4]:
show(guardian_topic0[['section','headline','trailText', 'tags', 'topic_key']], scrollY="500px", scrollCollapse=True)

In [8]:
section_clean_exp5 = clean_sections(guardian_topic0,[])

The dataset shrinked from 4451 to 2316

In [9]:
show(section_clean_exp5[['section','headline','trailText', 'tags', 'topic_key']], scrollY="500px", scrollCollapse=True)

In [10]:
tag_clean_topic0 = clean_tags(section_clean_exp5,[])

Kept 296 of 2316 articles related to ageing.

In [11]:
show(tag_clean_topic0[['section','headline','trailText', 'tags', 'topic_key']], scrollY="500px", scrollCollapse=True)