# Library Inclusion and Utilities

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from NLP import *
from itables import show
import itables.options as opt

/home/iskender/anaconda3/envs/bertopic-env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

show(tag_clean_df[['section','headline','trailText', 'tags']], scrollY="500px", scrollCollapse=True)

# Sanity Check

## Ageing-only corpus

In [42]:
topic_model, topic_info, g_no_longevity_out = analyze_bertopic(g_no_longevity, v_min_df=1, v_max_df=0.5,text_col="bodyText",top_n_words=30,
                                     save_csv=None)

2025-08-20 22:26:48,771 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████████████████████████████| 33/33 [05:59<00:00, 10.91s/it]
2025-08-20 22:32:48,826 - BERTopic - Embedding - Completed ✓
2025-08-20 22:32:48,826 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-08-20 22:32:49,758 - BERTopic - Dimensionality - Completed ✓
2025-08-20 22:32:49,759 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-08-20 22:32:49,797 - BERTopic - Cluster - Completed ✓
2025-08-20 22:32:49,799 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-08-20 22:32:51,189 - BERTopic - Representation - Completed ✓

In [43]:
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,222,-1_hiv_prison_coal_carbon,"[hiv, prison, coal, carbon, gaba, mushrooms, p...","[On an August morning in 2008, Tony Wyss-Coray..."
1,0,247,0_beauty_skincare_botox_makeup,"[beauty, skincare, botox, makeup, serum, cosme...",[1 Garnier Ambre Solaire Sensitive Face Fluid ...
2,1,81,1_fertility_migration_retirement age_older wor...,"[fertility, migration, retirement age, older w...","[People are a good thing, the most precious re..."
3,2,73,2_beds_term conditions_ambulance_commissioning,"[beds, term conditions, ambulance, commissioni...","[Displayed, not particularly prominently, on a..."
4,3,53,3_mice_stem cells_stem cell_gene,"[mice, stem cells, stem cell, gene, senescent,...",[Scientists have slowed down the ageing proces...
5,4,53,4_loneliness_calment_zak_divorce,"[loneliness, calment, zak, divorce, marsh, jea...","[Human societies, at all times and places, hav..."
6,5,50,5_prostate_lung_prostate cancer_cancer research,"[prostate, lung, prostate cancer, cancer resea...","[Survival rates for some types of cancer, incl..."
7,6,47,6_intuition_ear_alzheimer disease_people dementia,"[intuition, ear, alzheimer disease, people dem...","[Slow down, that used to be the mantra for mid..."
8,7,43,7_baker_aged care_care homes_rent,"[baker, aged care, care homes, rent, dilnot, b...",[A major shift in Tory housing policy in favou...
9,8,38,8_pollution_air pollution_cough_asthma,"[pollution, air pollution, cough, asthma, balm...",[Young Britons are dying from asthma at a high...
10,9,33,9_public sector_unions_union_strike,"[public sector, unions, union, strike, hutton,...",[R ubbish swirls through Southampton's shoppin...
11,10,24,10_biological age_horvath_epigenetic_kenyon,"[biological age, horvath, epigenetic, kenyon, ...",[Tech entrepreneur Bryan Johnson is talking ab...
12,11,18,11_fasting_portions_carb_dopamine,"[fasting, portions, carb, dopamine, veg, nuts,...","[Like everyone else in the world, my blood ran..."
13,12,17,12_funeral_palliative_lobban_palliative care,"[funeral, palliative, lobban, palliative care,...",[Dr BJ (Bruce) Miller is convinced that how we...
14,13,17,13_superannuation_state pension_pension age_in...,"[superannuation, state pension, pension age, i...",[Emily Millane – Per Capita On the train tonig...
15,14,14,14_venom_dom_citizen science_snakes,"[venom, dom, citizen science, snakes, citizen,...",[Today we celebrate the 350th anniversary of t...
16,15,14,15_menopause_oestrogen_fertility_vaginal,"[menopause, oestrogen, fertility, vaginal, uti...","[For my birthday last week, the algorithm gave..."
17,16,12,16_optimists_sonneberg_new optimists_boars,"[optimists, sonneberg, new optimists, boars, s...",[Under the bright lights of Berlin's inner cit...

In [32]:
full_keyword_getter(guardian_base_out)

-1.0 → ['discrimination', 'menopause', 'japan', 'older women', 'anger', 'dating', 'dancing', 'glasses', 'writers', 'pension', 'age uk', 'midlife crisis', '101', 'expectancy', 'life expectancy', 'bus', 'mothers', 'social care', 'workplace', 'ageing population', 'fat', 'winter', 'care homes', 'drugs', 'baby boomers', 'volunteering', 'hospitals', 'mr', 'edith', 'incontinence']
0.0 → ['cells', 'mice', 'drug', 'diseases', 'lifespan', 'biological', 'drugs', 'animals', 'cell', 'telomeres', 'senescent', 'factors', 'genes', 'gene', 'immune', 'genetic', 'scientific', 'senescent cells', 'ageing process', 'brains', 'age related', 'dna', 'trials', 'plasma', 'treatments', 'life expectancy', 'expectancy', 'biological age', 'stem', 'anti ageing']
1.0 → ['pension', 'expectancy', 'life expectancy', 'pensions', 'state pension', 'economy', 'poverty', 'employment', 'retirement age', 'pensioners', 'pension age', 'wealth', 'workforce', 'employers', 'fertility', 'statistics', 'inequality', 'rent', 'cohousing', 'harper', 'retirees', 'baby boomers', 'savings', 'older workers', 'healthy life', 'policies', 'ageing population', 'welfare', 'projected', 'sector']
2.0 → ['happiness', 'dull', 'millennials', 'boomer', 'adulthood', 'granny', 'ageist', 'partridge', 'older women', 'amis', 'alan', 'tom', 'pause', 'midlife crisis', 'graham', 'unhappy', 'boredom', 'pleasures', 'tomorrow', 'centenarians', 'satisfaction', 'remarks', 'psychology', 'lively', 'optimistic', 'gen', 'mature', 'grannies', 'stereotypes', 'bus']
3.0 → ['collagen', 'cosmetic', 'wrinkles', 'botox', 'anti ageing', 'cream', 'skincare', 'sun', 'serum', 'models', 'makeup', 'cells', 'brands', 'procedures', 'facial', 'older women', 'vitamin', 'product', 'filler', 'acid', 'ingredients', 'sunscreen', 'nirdosh', 'treatments', 'clothes', 'moisturiser', 'faces', 'creams', 'uv', 'grey hair']
4.0 → ['guardian letters', 'guardian readers', 'edition', 'print edition', 'click upload', 'readers click', 'share guardian', 'upload', 'like share', 'yorkshire', 'boris', 'kent', 'boris johnson', 'sussex', 'click visit', 'debate email', 'join debate', 'letters click', 'email guardian', 'com read', 'visit gu', 'letters theguardian', 'gu', 'com letters', 'gu com', 'theguardian', 'theguardian com', 'letters spread', 'publish best', 'submissions letters']
5.0 → ['aged care', 'social care', 'care homes', 'commission', 'providers', 'royal commission', 'residential', 'sector', 'resident', 'nurses', 'australians', 'nursing home', 'care services', 'staffing', 'councils', 'home care', 'health social', 'care quality', 'facility', 'providing', 'residential aged', 'adult social', 'age uk', 'nursing homes', 'care sector', 'remote', 'ratios', 'standards', 'unpaid', 'provider']
6.0 → ['muscle', 'shoulder', 'grip', 'sport', 'gym', 'muscles', 'sports', 'tennis', 'marathon', 'knee', 'arms', 'athletes', 'football', 'strength training', 'weights', 'swimming', 'pavey', 'movements', 'macdonald', 'trainer', 'swim', 'coach', 'intensity', 'leg', 'workouts', 'exercises', 'squat', 'heel', 'injury', 'cycling']
7.0 → ['end life', 'palliative', 'palliative care', 'suicide', 'assisted', 'life care', 'assisted dying', 'terminal', 'funeral', 'mavani', 'euthanasia', 'oregon', 'cemetery', 'burial', 'oncologist', 'terminally ill', 'assisted suicide', 'terminally', 'complications', 'elderly patients', 'impaired', 'hospitals', 'advance', 'tender', 'catholic', 'buried', 'insurance', 'aid', 'nursing home', 'hospice']
8.0 → ['chemirmir', 'grandad', 'eribon', 'conflict', 'assisted', 'anger', 'funeral', 'john campaign', 'mom', 'grieving', 'apartment', 'shanti', 'ashes', 'assisted dying', 'aunt', 'chase', 'texas', 'nursing home', 'cleaning', 'aged care', 'mourning', 'abandoned', 'items', 'uncle', 'guilty', 'gifts', 'ice cream', 'new life', 'prison', 'visitor']
9.0 → ['friendships', 'friendship', 'isolation', 'cities', 'lesley', 'romantic', 'social isolation', 'old friends', 'epidemic', 'solitude', 'age uk', 'poor health', 'widowed', 'close friends', 'dating', 'circles', 'boyfriend', 'volunteer', 'zoom', 'divorced', 'corner', 'connect', 'willett', 'independent age', 'socialising', 'councils', 'sharing', 'million people', 'acute', 'monthly']
10.0 → ['menopause', 'hrt', 'fertility', 'testosterone', 'symptoms', 'breast', 'osteoporosis', 'bone', 'breast cancer', 'oestrogen', 'menopausal', 'low testosterone', 'pregnancy', 'perimenopause', 'gp', 'hormone', 'women health', 'pills', 'bones', 'eggs', 'density', 'hormones', 'motherhood', 'replacement', 'frozen', 'hormonal', 'inquiry', 'gps', 'pregnant', 'increased risk']
11.0 → ['robot', 'digital', 'robots', 'tech', 'seniors', 'cash', 'sensors', 'climate', 'watson', 'startup', 'smartphone', 'banking', 'virtual', 'users', 'companion', 'robotic', 'conspiracy', 'parenting', 'honoré', 'mobile', 'device', 'tablet', 'smartphones', 'hub', 'san', 'technologies', 'apps', 'ai', 'francisco', 'san francisco']
12.0 → ['actors', 'aaron', 'rossellini', 'zeldin', 'actor', 'films', 'adams', 'nina', 'drama', 'gay', 'comedy', 'audience', 'beckett', 'acting', 'lake', 'hollywood', 'italy', 'oscar', 'production', 'characters', 'italian', 'actress', 'philip', 'scenes', 'directors', 'opera', 'jack', 'creativity', 'daniel', 'celebrity']
13.0 → ['nichols', 'films', 'stars', 'characters', 'cathy', 'actor', 'actors', 'bachelor', 'drama', 'ladies', 'hollywood', 'acting', 'older female', 'cast', 'cinema', 'seasons', 'aged women', 'turner', 'movies', 'bell', 'season', 'kelly', 'representation', 'oscar', 'older women', 'cox', 'ambition', 'actress', 'comedy', 'award']
14.0 → ['sex life', 'sexually', 'pamela', 'intimacy', 'sex lives', 'anonymous', 'sexuality', 'older men', 'pleasure', 'dating', 'topics', 'couples', 'libido', 'description', 'lee', 'appearing', 'submissions', 'desires', 'erotic', 'stuart', 'graham', 'psychotherapist', 'sensation', 'delay', 'treating', 'positions', 'theguardian', 'theguardian com', 'sexy', 'regrets']
15.0 → ['mick', 'beatles', 'band', 'mccartney', 'song', 'jagger', 'fans', 'singing', 'musicians', 'tour', 'rolling', 'harris', 'audience', 'guitar', 'fame', 'musical', 'performers', 'bob', 'levy', 'gay', 'touring', 'burn', 'guys', 'tiktok', 'roll', 'bands', 'crowd', 'cook', '52', 'grow old']
16.0 → ['calment', 'zak', 'frank', 'eddie', 'sue', 'jeanne', 'mosse', 'yvonne', 'novels', 'nelson', 'olivier', 'jeanne calment', 'investigation', 'russian', 'kramer', 'graham', 'james', 'dna', 'portraits', 'theory', 'fiction', 'memoir', 'gerontology', 'paris', 'images', 'portrait', 'painting', 'backdrop', 'supercentenarians', 'historical']
17.0 → ['dancing', 'dalman', 'ballet', 'dancers', 'moves', 'adelaide', 'bending', 'thompson', 'hughes', 'dancer', 'flight', 'contemporary', 'split', 'kramer', 'performing', 'classical', 'instructor', 'arts', 'flying', 'mature', 'olympic', 'artistic', 'creativity', 'shed', 'sport', 'flexibility', 'gym', 'paris', 'tour', 'performances']
18.0 → ['biden', 'trump', 'senate', 'joe biden', 'republican', 'senator', 'election', 'mcconnell', 'democratic', 'leaders', 'donald', 'democrats', 'presidential', 'donald trump', 'leader', 'elected', 'congress', 'candidates', 'voters', 'politicians', 'obama', 'generational', 'vote', '2024', 'leadership', 'new generation', 'polls', 'average age', 'speaker', 'united states']
19.0 → ['napping', 'insomnia', 'daytime', 'asleep', 'awake', 'bedtime', 'nap', 'timing', 'night sleep', 'naps', 'waking', 'volume', 'woke', 'females', 'foster', 'noise', 'slept', 'patterns', 'habits', 'caffeine', 'adolescence', 'alzheimer disease', 'previous research', 'males', 'puberty', 'genetic', 'occurs', 'cognitive decline', 'cognitive impairment', 'brain health']
20.0 → ['drivers', 'older drivers', 'driver', 'licence', 'mandatory', 'crash', 'roads', 'assessment', 'newton', 'vehicle', 'premium', 'wheel', 'victoria', 'fatal', 'victorian', 'accidents', 'insurance', 'safely', 'injuries', 'assessments', 'motor', 'ice cream', 'injury', 'reactions', 'keys', 'involving', 'transport', '97', 'ice', 'independence']

## Across-tags corpus by core keys

In [3]:
g = pd.read_csv("../GuardianAPI/guardian_base_across_tags.csv")
g_age_only = pd.read_csv('../GuardianAPI/guardian_ageing_tag_only.csv')
g_no_longevity = pd.read_csv('../GuardianAPI/guardian_base_across_tags_wo_longevity.csv')
guardian = pd.read_csv("../GuardianAPI/guardian_allkeys_unrestricted_2010-2012.csv")
for year in range(2013, 2025+1, 3):
    g = pd.read_csv(f"../GuardianAPI/guardian_allkeys_unrestricted_{year}-{year+2}.csv")
    guardian = pd.concat([g,guardian],ignore_index=True)

In [4]:
g = clean_sections(g,[])
g_age_only = clean_sections(g_age_only,[])
g_no_longevity = clean_sections(g_no_longevity,[])
guardian = clean_sections(guardian,[])

The dataset shrinked from 1086 to 390
The dataset shrinked from 1479 to 1124
The dataset shrinked from 1650 to 1056
The dataset shrinked from 23990 to 8735

In [7]:
topic_model, topic_info, guardian = analyze_bertopic(guardian, v_min_df=1, v_max_df=0.5,text_col="bodyText",top_n_words=30,
                                     save_csv=None)

2025-08-26 16:10:29,196 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|████████████████████████████████| 273/273 [51:31<00:00, 11.32s/it]
2025-08-26 17:02:02,205 - BERTopic - Embedding - Completed ✓
2025-08-26 17:02:02,206 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-08-26 17:02:14,109 - BERTopic - Dimensionality - Completed ✓
2025-08-26 17:02:14,110 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-08-26 17:02:17,564 - BERTopic - Cluster - Completed ✓
2025-08-26 17:02:17,573 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-08-26 17:02:30,607 - BERTopic - Representation - Completed ✓

In [ ]:
guardian.to_csv("")

In [11]:
pd.set_option('display.max_rows', None)
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,2578,-1_phd_carers_dementia_yoga,"[phd, carers, dementia, yoga, health social, n...",[Bertie’s of Bay This heritage clothes brand’s...
1,0,213,0_cells_mice_dna_cell,"[cells, mice, dna, cell, gene, stem, genetic, ...",[When last year’s Nobel prize for chemistry wa...
2,1,186,1_restaurant_cheese_chef_meat,"[restaurant, cheese, chef, meat, cooking, sauc...",[People *** Paris Rosina and the return of sup...
3,2,178,2_voters_corbyn_tory_tories,"[voters, corbyn, tory, tories, referendum, lib...",[Labour members and supporters face an awesome...
4,3,139,3_gas_carbon_electricity_coal,"[gas, carbon, electricity, coal, renewable, nu...",[The UK will close all coal-fired power plants...
5,4,135,4_people aged_ageism_old people_aged 65,"[people aged, ageism, old people, aged 65, age...",[One in five pensioners – more than 2 million ...
6,5,130,5_skincare_collagen_cream_beauty,"[skincare, collagen, cream, beauty, serum, moi...","[For the face The Inkey List Squalane Oil, £8...."
7,6,114,6_botox_cosmetic_procedures_beauty,"[botox, cosmetic, procedures, beauty, fillers,...","[Do you know what a tweakment is? I didn’t, no..."
8,7,104,7_councils_dilnot_cap_care costs,"[councils, dilnot, cap, care costs, adult soci...",[More older people and citizens with disabilit...
9,8,96,8_trousers_clothes_dress_designer,"[trousers, clothes, dress, designer, shirt, wa...","[As the seasons change, it can be tempting to ..."
10,9,94,9_societyguardian_voluntary sector_blog_public...,"[societyguardian, voluntary sector, blog, publ...",[Sign up to Society daily email briefing Today...
11,10,93,10_fitness_muscle_gym_muscles,"[fitness, muscle, gym, muscles, workout, physi...",[When Baz Luhrmann called the body “the greate...
12,11,90,11_trusts_stevens_health service_nhs england,"[trusts, stevens, health service, nhs england,...",[Theresa May has rejected claims from senior m...
13,12,82,12_obr_chancellor_fiscal_public finances,"[obr, chancellor, fiscal, public finances, bor...",[How bad is it going to get? As chair of the O...
14,13,81,13_cancers_breast_breast cancer_screening,"[cancers, breast, breast cancer, screening, di...","[At least 115,000 cancer patients in England a..."
15,14,79,14_gps_gp_general practice_family doctors,"[gps, gp, general practice, family doctors, ap...",[The health secretary Jeremy Hunt will unveil ...
16,15,78,15_nuclear_reactors_sellafield_nuclear power,"[nuclear, reactors, sellafield, nuclear power,...",[Jeremy Hunt has kickstarted a fresh push into...
17,16,77,16_ambulance_beds_departments_nhs england,"[ambulance, beds, departments, nhs england, ad...","[Paramedics last year spent 500,000 hours outs..."
18,17,75,17_dementia_alzheimer_diagnosis_people dementia,"[dementia, alzheimer, diagnosis, people dement...",[Dementia has now overtaken coronary heart dis...
19,18,74,18_thames_sewage_ofwat_thames water,"[thames, sewage, ofwat, thames water, water co...","[Thirty-five years ago, investors flocked to b..."
20,19,70,19_shields_actor_films_comedy,"[shields, actor, films, comedy, hollywood, cha...",[If escaping the world by running for the hill...
21,20,70,20_wine_wines_chardonnay_pinot,"[wine, wines, chardonnay, pinot, bottle, blanc...","[White wines under £10 Tesco Finest St-Mont, F..."
22,21,69,21_assisted_assisted dying_palliative_palliati...,"[assisted, assisted dying, palliative, palliat...",[Which is worse? Being driven to end your life...
23,22,67,22_marriage_divorce_married_couples,"[marriage, divorce, married, couples, dating, ...","[They are called the ""silver splitters"", or gr..."
24,23,67,23_concealer_makeup_powder_lip,"[concealer, makeup, powder, lip, glow, finish,...","[Sacrilege for a beauty editor to admit, but w..."
25,24,66,24_immigration_migration_migrants_immigrants,"[immigration, migration, migrants, immigrants,...",[As Australia reached a population of 25 milli...
26,25,66,25_monarchy_prince_monarch_diana,"[monarchy, prince, monarch, diana, elizabeth, ...",[What do you give the wealthiest woman in the ...
27,26,65,26_stores_retail_retailer_shoppers,"[stores, retail, retailer, shoppers, high stre...",[“We have a plan but it’s a high wire act and ...
28,27,64,27_patriarchy_republican_democrats_republicans,"[patriarchy, republican, democrats, republican...","[In 2006, Kansas Republican Sam Brownback was ..."
29,28,63,28_sexual_sex life_intimacy_sexually,"[sexual, sex life, intimacy, sexually, pleasur...","[Where has my sexual desire gone, and how do I..."
30,29,61,29_rock_album_madonna_songs,"[rock, album, madonna, songs, song, vocal, pop...",[I got into this business to write great songs...
31,30,60,30_healthy life_marmot_expect live_inequalities,"[healthy life, marmot, expect live, inequaliti...",[England’s richest people are living for a dec...
32,31,58,31_temperatures_fires_ice_warming,"[temperatures, fires, ice, warming, florida, f...",[THE EARTH IS WARMER NOW THAN IT HAS EVER BEEN...
33,32,57,32_fertility_population growth_milk_births,"[fertility, population growth, milk, births, d...",[The House of Commons will today debate the mo...
34,33,56,33_chemotherapy_oncologist_cancer patients_dia...,"[chemotherapy, oncologist, cancer patients, di...","[“You’re an oncologist, isn’t that depressing?..."
35,34,55,34_loneliness_lonely_friendships_friendship,"[loneliness, lonely, friendships, friendship, ...",[Almost three-quarters of older people in the ...
36,35,55,35_coal_electricity_renewable_renewable energy,"[coal, electricity, renewable, renewable energ...",[Australia’s chief scientist says a new clean ...
37,36,55,36_menopause_testosterone_hrt_symptoms,"[menopause, testosterone, hrt, symptoms, oestr...",[Fifty-one per cent of the population will exp...
38,37,52,37_fasting_bacon_protein_meat,"[fasting, bacon, protein, meat, processed, foo...",[‘Nutrition is one of the hardest sciences to ...
39,38,50,38_clothes_cotton_fabric_leather,"[clothes, cotton, fabric, leather, wool, cashm...","[This week more than most, we have been hearin..."
40,39,50,39_sciences_universities_scientist_physics,"[sciences, universities, scientist, physics, j...","[In March this year, the US Congress voted to ..."
41,40,49,40_homelessness_social housing_tenants_homeless,"[homelessness, social housing, tenants, homele...",[The University of York’s analysis on the stat...
42,41,49,41_grey hair_bald_beard_dye,"[grey hair, bald, beard, dye, colour, silver, ...",[The days when women are encouraged to cover u...
43,42,48,42_north sea_oil gas_gas_shell,"[north sea, oil gas, gas, shell, bp, fossil, s...","[Total, one of the biggest energy firms operat..."
44,43,48,43_public sector_pensions_hutton_unions,"[public sector, pensions, hutton, unions, stri...",[Unions reacted with predictable anger at the ...
45,44,47,44_older workers_employers_state pension_aged 50,"[older workers, employers, state pension, aged...","[Lisa Griffiths, a 61-year-old special needs n..."
46,45,47,45_fertility_sperm_eggs_ivf,"[fertility, sperm, eggs, ivf, egg, pill, pregn...",[Men. You had one job. And now look what’s hap...
47,46,46,46_merkel_germans_macron_refugees,"[merkel, germans, macron, refugees, far right,...",[You would hardly know this is general electio...
48,47,46,47_lansley_health service_privatisation_reorga...,"[lansley, health service, privatisation, reorg...",[So the private healthcare industry is licking...
49,48,43,48_hockey_mining_unemployment_unemployment rate,"[hockey, mining, unemployment, unemployment ra...",[Joe Hockey in his time as treasurer certainly...
50,49,42,49_cognitive_dementia_brain health_alzheimer,"[cognitive, dementia, brain health, alzheimer,...",[Being physically fit can lower the risk of de...
51,50,41,50_rent_landlords_rents_tenants,"[rent, landlords, rents, tenants, renting, new...",[A major shift in Tory housing policy in favou...
52,51,41,51_voters_olds_voting_year olds,"[voters, olds, voting, year olds, boomers, mil...",[Here’s a nightmare for those of us who want a...
53,52,39,52_pensioners_boomers_intergenerational_baby b...,"[pensioners, boomers, intergenerational, baby ...",[‘Baby boomers have built an empire and empire...
54,53,39,53_heroin_cannabis_jake_cocaine,"[heroin, cannabis, jake, cocaine, drug use, ad...","[The good news, according to the latest govern..."
55,54,38,54_putin_russia_russian_ukraine,"[putin, russia, russian, ukraine, moscow, sovi...",[Nothing in politics is as dangerous as a popu...
56,55,37,55_councils_local government_public services_l...,"[councils, local government, public services, ...",[Furious local government leaders are accusing...
57,56,37,56_ai_pilot_health care_guardian professional,"[ai, pilot, health care, guardian professional...",[Telehealth has the potential to reduce hospit...
58,57,37,57_nurses_nursing_nurse_recruitment,"[nurses, nursing, nurse, recruitment, midwives...",[Brexit is set to cause a severe shortage of n...
59,58,36,58_universities_higher education_engineering_h...,"[universities, higher education, engineering, ...",[University leaders are in the dock of public ...
60,59,36,59_older women_vogue_modelling_moss,"[older women, vogue, modelling, moss, clothes,...","[We're all Fabulous Fashionistas now, if the p..."
61,60,36,60_prison_prisoners_prisons_inmates,"[prison, prisoners, prisons, inmates, prisoner...","[Ten days before Christmas, in the middle of t..."
62,61,35,61_flowers_plants_flower_plant,"[flowers, plants, flower, plant, nursery, seed...",[When your dedication to cut flowers rivals El...
63,62,33,62_electric_cars_vehicles_charging,"[electric, cars, vehicles, charging, battery, ...","[You drive home and plug in your electric car,..."
64,63,33,63_inflation_gdp_bailey_bank england,"[inflation, gdp, bailey, bank england, pound, ...",[Pound slides to reach 10-month low Renewed Br...
65,64,33,64_alcohol_units_drinkers_wine,"[alcohol, units, drinkers, wine, booze, drunk,...","[January is again upon us, marking a month of ..."
66,65,32,65_atomic_lab_blog_species,"[atomic, lab, blog, species, podcast, amazon, ...",[This week’s biggest stories It’s a significan...
67,66,32,66_care workers_baker_recruitment_care worker,"[care workers, baker, recruitment, care worker...",[Ministers have been warned of a “dangerous sh...
68,67,32,67_sport_swimming_marathon_swim,"[sport, swimming, marathon, swim, williams, cy...","[‘If we’re in the gym, that’s where the kids w..."
69,68,32,68_middle age_wisdom_veteran_grandchildren,"[middle age, wisdom, veteran, grandchildren, m...","[When my first-born was three, he was talking ..."
70,69,31,69_space station_nasa_astronauts_orbit,"[space station, nasa, astronauts, orbit, space...","[A chartered spaceflight for India, Poland and..."
71,70,31,70_egypt_military_arab_regime,"[egypt, military, arab, regime, protesters, al...",[If there is one feature that would best descr...
72,71,31,71_grief_mum_dad_funeral,"[grief, mum, dad, funeral, trauma, dementia, g...",[I’m imagining myself teaching a class on grie...
73,72,31,72_chinese_beijing_xi_hong,"[chinese, beijing, xi, hong, hong kong, kong, ...",[“Because most Chinese are satisfied with the ...
74,73,30,73_covid 19_virus_vaccine_lockdown,"[covid 19, virus, vaccine, lockdown, coronavir...","[Over the past couple of months, deaths in Eng..."
75,74,30,74_disabled_disability_disabled people_autism,"[disabled, disability, disabled people, autism...",[When I began to write a book four years ago a...
76,75,30,75_drivers_bikes_bike_lorry,"[drivers, bikes, bike, lorry, cycling, traffic...",[It's not the best of starts. I've only been i...
77,76,28,76_obesity_overweight_obese_malnutrition,"[obesity, overweight, obese, malnutrition, jun...",[The decision to delay a ban on supermarket of...
78,77,28,77_zealand_new zealand_amazon_silicon valley,"[zealand, new zealand, amazon, silicon valley,...",[The abiding problem with writing about digita...
79,78,27,78_mental illness_therapy_health problems_heal...,"[mental illness, therapy, health problems, hea...",[People facing mental health crises will be ab...
80,79,27,79_rail_trains_railway_roads,"[rail, trains, railway, roads, developers, coa...",[At the heart of the Conservative promise for ...
81,80,27,80_eurozone_greece_euro_currency,"[eurozone, greece, euro, currency, greek, bail...",[Eurozone growth leapt ahead of the UK and US ...
82,81,27,81_airline_aircraft_planes_plane,"[airline, aircraft, planes, plane, fleet, pass...",[It may be slightly less profitable and boast ...
83,82,27,82_hearing loss_health service_upfront_health ...,"[hearing loss, health service, upfront, health...",[Lend me your ears. What follows is a plea abo...
84,83,27,83_dogs_pets_pet_cats,"[dogs, pets, pet, cats, animals, owners, anima...",[Scientists are targeting a new set of recruit...
85,84,25,84_state pension_pension age_pensions_retireme...,"[state pension, pension age, pensions, retirem...","[Last week I spoke to Barbara Bates, who works..."
86,85,25,85_methane_emissions_gas_oil gas,"[methane, emissions, gas, oil gas, epa, leaks,...",[The United States has announced a major crack...
87,86,24,86_imf_economies_global economy_monetary,"[imf, economies, global economy, monetary, rec...",[The International Monetary Fund (IMF) has cut...
88,87,24,87_spacecraft_nasa_mars_moon,"[spacecraft, nasa, mars, moon, universe, solar...","[On a chilly March morning, Steve Howard, aged..."
89,88,24,88_gin_rum_beer_barrels,"[gin, rum, beer, barrels, whisky, barrel, craf...","[Public, the newly crowned Observer Food Month..."
90,89,24,89_loneliness_games_clare_isolation,"[loneliness, games, clare, isolation, siblings...","[For more than a decade, 71-year-old Harry Sey..."
91,90,24,90_sunscreen_spf_cream_makeup,"[sunscreen, spf, cream, makeup, skins, uv, min...","[This is groundhog day. Because, of course, we..."
92,91,24,91_malcolm_childless_mothers_parenting,"[malcolm, childless, mothers, parenting, mothe...","[It’s the middle of a dark, November night, an..."
93,92,24,92_bat_species_birds_velvet,"[bat, species, birds, velvet, bird, nest, trop...",[Farmland birds in Britain have declined to th...
94,93,24,93_church_catholic_religious_christian,"[church, catholic, religious, christian, roman...","[For decades, there has been a cultural narrat..."
95,94,24,94_murdoch_journalism_journalists_newspapers,"[murdoch, journalism, journalists, newspapers,...",[There were two very revealing moments in Rupe...
96,95,23,95_pollution_air pollution_diesel_wood,"[pollution, air pollution, diesel, wood, burni...",[Three years ago I had a heart operation that ...
97,96,23,96_inequality_income tax_taxation_households,"[inequality, income tax, taxation, households,...",[Almost a quarter of all household wealth in t...
98,97,23,97_buildings_trusts_backlog_maintenance,"[buildings, trusts, backlog, maintenance, crum...",[The NHS in England has a record repair bill o...
99,98,23,98_novel_fiction_novels_literary,"[novel, fiction, novels, literary, classic, pr...",[No one can say precisely why John Williams's ...
100,99,23,99_junior_junior doctors_strike_bma,"[junior, junior doctors, strike, bma, gps, sev...",[Whose motives do you trust more: junior docto...
101,100,22,100_unemployment_inflation_congress_republicans,"[unemployment, inflation, congress, republican...",[On 27 March Donald Trump signed the Cares Act...
102,101,21,101_violence_trans_gay_older women,"[violence, trans, gay, older women, ted, victi...","[Judging by column inches alone, you might be ..."
103,102,21,102_care homes_care home_providers_cqc,"[care homes, care home, providers, cqc, privat...",[The dire consequences of neglecting social ca...
104,103,21,103_elephants_wildlife_rhino_ivory,"[elephants, wildlife, rhino, ivory, elephant, ...",[Ivory is the cocaine of south-east Asia. Mill...
105,104,21,104_read guardian_guardian letters_edition_con...,"[read guardian, guardian letters, edition, con...",[Your editorial on pubs (30 December) states t...
106,105,20,105_ftse_ftse 100_shareholders_investors,"[ftse, ftse 100, shareholders, investors, inde...","[He's the City's kingmaker, who would have dec..."
107,106,20,106_emissions_renewable_renewable energy_carbon,"[emissions, renewable, renewable energy, carbo...","[Australia’s climate change minister, Chris Bo..."
108,107,20,107_african_continent_human rights_elections,"[african, continent, human rights, elections, ...",[There are moments when the international comm...
109,108,19,108_tree_trees_forest_oak,"[tree, trees, forest, oak, species, forests, w...",[When Kevin Martin was a child he spent days b...
110,109,19,109_nerve_rehabilitation_term conditions_stroke,"[nerve, rehabilitation, term conditions, strok...",[Our NHS is under attack from all angles. Peop...
111,110,19,110_medicines_medication_prescribed_guidelines,"[medicines, medication, prescribed, guidelines...","[Last week, we learned that 43% of men and 50%..."
112,111,19,111_iran_reed_iranian_korean,"[iran, reed, iranian, korean, reporter, tank, ...","[Growing up in England, people would always as..."
113,112,19,112_scottish_snp_border_revenues,"[scottish, snp, border, revenues, referendum, ...",[When Nicola Sturgeon announced she was quitti...
114,113,18,113_skin cancer_melanoma_uv_sunscreen,"[skin cancer, melanoma, uv, sunscreen, rays, s...",[Shades? SPF50 suncream? Wide-brimmed hat? For...
115,114,18,114_sleeping_caffeine_asleep_cognitive,"[sleeping, caffeine, asleep, cognitive, partic...",[Do you find yourself getting much less sleep ...
116,115,17,115_plastic_bags_materials_rubbish,"[plastic, bags, materials, rubbish, recycling,...","[The smell in Natural Weigh, a zero-waste shop..."
117,116,17,116_hall_alter_cards_lockdown,"[hall, alter, cards, lockdown, marathon, tea, ...","[""Toto... I've got a feeling we're not in Kans..."
118,117,17,117_farm_farmers_farming_farms,"[farm, farmers, farming, farms, cannabis, agri...",[When the vast expanse of rural Iowa was carve...
119,118,17,118_crime_protest_protesters_officers,"[crime, protest, protesters, officers, occupat...",[A conservative is “a liberal who has been mug...
120,119,17,119_alzheimer_amyloid_alzheimer disease_dementia,"[alzheimer, amyloid, alzheimer disease, dement...","[As Davangere Devanand, a neurologist at Colum..."
121,120,17,120_hiv_aids_steve_virus,"[hiv, aids, steve, virus, diagnosed, gay, stig...",[The most recent data from Public Health Engla...
122,121,17,121_pupils_teachers_teacher_teaching,"[pupils, teachers, teacher, teaching, maths, p...",[Plans to push ahead with reopening schools in...
123,122,17,122_lansley_commissioning_clegg_lib,"[lansley, commissioning, clegg, lib, david cam...",[David Cameron admitted that he had made mista...
124,123,17,123_pharmaceutical_earnings_vaccine_maker,"[pharmaceutical, earnings, vaccine, maker, swi...","[The GlaxoSmithKline CEO, Sir Andrew Witty, sa..."
125,124,17,124_coal_natural gas_gas_carbon,"[coal, natural gas, gas, carbon, plants, elect...",[All eyes are on the oil industry as prices co...
126,125,16,125_care workers_wage_minimum wage_clubs,"[care workers, wage, minimum wage, clubs, aged...","[About 160,000 care workers are paid less than..."
127,126,16,126_pfas_chemicals_epa_chemical,"[pfas, chemicals, epa, chemical, compounds, dr...","[In 2002, the French multinational Saint-Gobai..."
128,127,16,127_buildings_concrete_pupils_blocks,"[buildings, concrete, pupils, blocks, estate, ...",[Parents and pupils across the country prepari...
129,128,16,128_whales_whale_species_marine,"[whales, whale, species, marine, fish, waters,...",[More than 300 beluga whales and 60 orcas rema...
130,129,16,129_advent_calendar_gift_wedding,"[advent, calendar, gift, wedding, amazon, fest...",[The gift guides are out again! Regular reader...
131,130,16,130_brazil_hungry_inequality_universal credit,"[brazil, hungry, inequality, universal credit,...","[In inimitable Brazilian style, the upcoming n..."
132,131,15,131_libya_articles_cup_italian,"[libya, articles, cup, italian, kings, request...","[• Driving examiners have been on strike, not ..."

In [14]:
show(guardian[guardian['topic']==141])